### ISSUE TITLE
Vern

### ISSUE THREAD

**Issue by vcomney** [cop1000/cop1000#1]
Hello, all. My name is Vern. I take online classes bc of extended travel for work. Currently in San Francisco at the moment working on something. I'm married with a 9 year old daughter. I've been a musician for 21 years (realizing that is likely longer than most of my classmates have been alive), but I'm still just a punk kid at heart. I'm also a surgical assistant by trade with medical sales/bartending experience. I like wine, traveling, whiskey, cigars, writing, music composition, cooking, standup comedy, fun company, and of course, good tunes played super loud. Looking forward to learning something new here. Hope this goes well.

**Comment by aleallopez** [comment]
Hi , my name is Agnes i am from Puerto Rico  currently living in Orlando  this is my first online class , and its on my 21 birthday yay!!.. what a fun day, i have an Associates degree in nursing  and I am only a student. I hope that this goes well as my first only class

**Comment by hectorsector** [comment]
Welcome @vcomney! I travel a lot for work, too, and often to San Francisco 😉 Have you been there before?

**Comment by vcomney** [comment]
@hectorsector Yes, I've spent a lot of time in the Bay Area over the past year. It's such an awesome place to be when I'm here. The weather is the best. Any favorite spots to eat?

**Comment by vcomney** [comment]
@aleallopez happy birthday! 21? That makes me feel old at 36, lol. My wife is a nurse and, despite the stresses, it is certainly a rewarding field to be in. Lots of opportunities to grow. Good luck with the class.

**Comment by tylerch8** [comment]
That's so cool you've been into music for that long! I'm jealous you're in San Francisco. I hear it's a really great city! I'm also long distance too- living in Melbourne. Ok, so it's only an hour away from Orlando and not as far as California... :)

**Comment by hectorsector** [comment]
> Any favorite spots to eat?

@vcomney have you tried [Dandelion Chocolate](https://www.yelp.com/biz/dandelion-chocolate-san-francisco)? 😋

**Comment by vcomney** [comment]
@hectorsector I haven't been there before. I see it's by Dolores Park, which I love. I'll pop over there next time I'm over that way. I'll mention it to my brother who lives in the city.

**Comment by hectorsector** [comment]
Great work @emerced2! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @robpb24! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @jjyates4! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @jriosrodriguez! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @AAR0NPI3RC3! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @nshort1! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @cristivela1217! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @lminks! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @marxspawn! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @Lolivo! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @Mikedaris94! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @aalevane! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @Jomarm92x! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @mdean19! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @tiagaloppe! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @aleallopez! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @rbowser5! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @MCastro46! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
Great work @Jordan-Hosein! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
