### ISSUE TITLE
Tyler

### ISSUE THREAD

**Issue by tylerch8** [cop1000/cop1000#10]
Hi!

I'm Tyler. I graduated from UCF a couple years ago in Social Science but now I'm going back to pursue Computer Science (big change, I know). I used to program a lot many years ago but fell out of it. So starting this class is a new beginning for me! The field of UX/User experience interests me. I'm currently a supervisor for Starbucks Coffee and I do love coffee, but my other interests include- travel, higher education, sushi, cats and of course technology. It's great to be here and I look forward to working with everyone one! 

![panthermural](https://cloud.githubusercontent.com/assets/21182959/18062281/26f82b84-6df4-11e6-9aaf-74a7d13e9faa.jpg)

**Comment by rbanton** [comment]
Nice! I do a rudimentary form of coding on a online game that i play every so often. Im hoping i can really take a lot from this class, especially since im going to be an Astrophysicist :)

**Comment by hectorsector** [comment]
Welcome @tylerch8! I am big 🍣 fanatic myself. Do you have a favorite place in Orlando? Bikurri Sushi near Mills is amazing!

**Comment by tylerch8** [comment]
@rbanton That is really awesome! I'd love to hear more about coding for an online game!

**Comment by tylerch8** [comment]
@hectorsector Sushi is the best! I've enjoyed Amura on Sandlake and Shakai in Downtown. I'll definitely have to check out Bikurri though. My favorite is in Brevard- a place called Thai Thai and there are a few locations there.

**Comment by hectorsector** [comment]
Great work @tylerch8! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
