### ISSUE TITLE
emerced2's Project 1 submission

### ISSUE THREAD

**Issue by emerced2** [cop1000/cop1000#101]
Paste your web site's published URL here: https://emerced2.github.io/

Check each of the following boxes to ensure you can score 💯 

- [👍] Bootstrap is used.
- [👍] Web site contains images.
- [👍] Web site contains text.
- [👍] Web site contains external links.
- [👍] All of the web site's content can be accessed just by scrolling.
- [👍] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [👍] The web site contains original content.
- [👍] The web site doesn't contain inappropriate content.
- [👍] The web site is published to GitHub Pages.
- [👍] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Love the content on your site @emerced2! I did notice that although you use Bootstrap, your images aren't correctly styled. They should resize when you resize your window if you did it correctly. You might want to correct that.

**Comment by hectorsector** [comment]
Great work @emerced2! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
