### ISSUE TITLE
Joseph Bean

### ISSUE THREAD

**Issue by PlusCode** [cop1000/cop1000#102]
Hi everyone 
I live in Davenport Fl, I'm working toward a TC in programing. I hope to learn a lot in this class, ready to get started. Here's to a great semester :)

**Comment by Hkhan15** [comment]
Nice to meet you, and best of luck for the semester.

**Comment by hectorsector** [comment]
Welcome @PlusCode! What are some of your personal interests and why are you interested in this class?

**Comment by jenny0325** [comment]
Hello @PlusCode it's nice to meet you, I hope this semester treats you well.

**Comment by PlusCode** [comment]
Hi jenny0325

It's nice to meet you also, hopefully we all will have a great semester, I look forward to working with you [😊]

________________________________

**Comment by PlusCode** [comment]
Hello @hectorsector  
I have background in IT and have always wanted to learn programming & webpage development , so here I am :)

**Comment by hectorsector** [comment]
Great work @PlusCode! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
