### ISSUE TITLE
Hello World! I'm Javier Barea

### ISSUE THREAD

**Issue by Javier-of-the-Rich-Port** [cop1000/cop1000#103]
I am Javier Barea and I was born in Ponce, Puerto Rico and moved to Orlando when I was 2. I am taking this class to get a firm handle on the basics as opposed to haphazard mess of skills I'ved cobbled together through highschool and First Robotics.

Recently I started reading 1001 Arabian Nights.

(I will add a picture soon)

**Comment by lucianoh** [comment]
Hey Javier, its nice to meet you. Hopefully this class will help you improve upon your coding skills.

**Comment by hectorsector** [comment]
Great to meet you @Javier-of-the-Rich-Port 👋 Not to make you feel any worse... but years-in I still feel like my skill set is a haphazard mess 😉

**Comment by hectorsector** [comment]
Great work @Javier-of-the-Rich-Port! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
