### ISSUE TITLE
Hidayat Khan

### ISSUE THREAD

**Issue by Hkhan15** [cop1000/cop1000#104]
Hello class my name is Hidayat. I started this class today, My major is IT  (Information Technology). Which require me to take this class and I am personally interested in this class because I like dealing computers or technology.

**Comment by hectorsector** [comment]
Welcome @hkhan15! Tell us a little bit more about you -- have you tried to program before? If so, in what language? What are you hoping to learn?

**Comment by Hkhan15** [comment]
no this is my first time of programing.

**Comment by hectorsector** [comment]
Great work @Hkhan15! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
