### ISSUE TITLE
Luciano Harris

### ISSUE THREAD

**Issue by lucianoh** [cop1000/cop1000#105]
Hello class my name is Luciano and I'm currently pursuing my associates in network engineering. I enrolled myself in this course because it is a requirement for my degree. My hobbies include playing video games and listening to music.

**Comment by Nuridean** [comment]
Nice meeting you!

**Comment by hectorsector** [comment]
Welcome to the course @lucianoh! What kind of video games and music do you like?

**Comment by mariadodoll** [comment]
Hello Luciano, welcome to the class I also enrolled because it was a requirement but I am excited to learn the basics of programming in order to move up to more advanced programming.

**Comment by lucianoh** [comment]
@hectorsector In terms of games, I really enjoy RPGs and platformers and my favorite genre of music is jazz.

**Comment by hectorsector** [comment]
Great work @lucianoh! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
