### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by Selia97** [cop1000/cop1000#106]
Good morning everyone, my name is Selia from Kissimmee FL. I am very excited to be starting this class. This is my first computer programing class required for my major, Information Technology. During my free time you would find me working because I am a workaholic and working = money.

**Comment by jmedian90** [comment]
Hello Selia! out of curiosity what is it you plan to be when you get your degree? And I can relate to that last sentence.

**Comment by hectorsector** [comment]
Welcome @selia97.

> what is it you plan to be when you get your degree

I'd like to know the answer to this, too!

**Comment by Selia97** [comment]
I plan on pursuing my career within cyber security.

**Comment by hectorsector** [comment]
Great work @Selia97! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
