### ISSUE TITLE
Nuridean M Mubarak

### ISSUE THREAD

**Issue by Nuridean** [cop1000/cop1000#107]
Hi!
I'm Nuridean and this my first year in college and I'm exited to start this class with you all! Playing games is one of my interests, a couple of those games would be League, Starcraft, and I try to go to smash tournaments to expose myself to different kinds of people. I currently work at Chick-Fil-A also. 
![76905_10100111778696442_4463376_n](https://cloud.githubusercontent.com/assets/7443478/19045042/e1098f50-8964-11e6-9077-f612f727ec22.jpg)
(Halloween 2010)

**Comment by hectorsector** [comment]
What a great picture, @Nuridean! It's great to meet you and learn a little bit about your interests. I'm a  big gamer, also.

**Comment by kpatelbz** [comment]
Great thought on your profile pic. I look forward to speaking with you about the speak in the future.

**Comment by hectorsector** [comment]
Great work @Nuridean! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
