### ISSUE TITLE
Hello everyone! My name is James Medina

### ISSUE THREAD

**Issue by jmedian90** [cop1000/cop1000#108]
I have never been very good at talking about myself but here goes nothing. I was born in California 23 years ago but have spent most of my life here in Florida. I stand 5'9 so i am not very tall. The reason i am in this class is because i am trying to become a video game tester and designer. That's all i got if you have any questions though i will answer

**Comment by hectorsector** [comment]
Welcome, @jmedian90! I'm not great talking about myself either so I certainly appreciate you getting out there and trying it!

**Comment by hectorsector** [comment]
Great work @jmedian90! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
