### ISSUE TITLE
Clayton Higgs

### ISSUE THREAD

**Issue by claytonhiggs** [cop1000/cop1000#109]
Hi, my name's Clayton. I'm 5'7, was born and raised in Florida, and am currently an English teacher.  I'm majoring in computer science so one day I can design video games. It's my dream to have my own company one day, and I believe learning to program will give me a lot of potential when it comes to establishing a business. My hobbies are producing music and table tennis. I look forward to what I'll be learning in this class. 

![14332947_1204185572978211_5158191809365610778_n-2](https://cloud.githubusercontent.com/assets/22600013/19049230/8f2472e6-8977-11e6-9ec2-7daf3a67c33a.jpg)

**Comment by StephanNears** [comment]
Welcome! @claytonhiggs , Great to meet ya! Hope we can all enjoy learning in this class.

**Comment by hectorsector** [comment]
Welcome @claytonhiggs! What kind of school do you teach English at?

**Comment by hectorsector** [comment]
@claytonhiggs I don't see you on my class roll anymore -- if this is a mistake please don't hesitate to message me privately.
