### ISSUE TITLE
Raymond Banton

### ISSUE THREAD

**Issue by rbanton** [cop1000/cop1000#11]
Hi everyone, my name is Raymond Banton and I am interested in this class because i have done a little rudimentary coding in the past and I am becoming an Astrophysicist. Some things that i enjoy in my spare time are video games and playing piano.
![12294717_1124622050896141_6085724924350235503_n](https://cloud.githubusercontent.com/assets/21318198/18064336/e6d96a82-6dfc-11e6-8d33-d3c310a61dd4.jpg)

**Comment by hectorsector** [comment]
Welcome @rbanton! I've been trying to learn how to play the piano again. I used to, a long time ago, and have not practiced. So I bought myself a new keyboard last year and I've been putting off practicing.

**Comment by rbanton** [comment]
@hectorsector Nice! Theres a great app called yousician that helps you learn pop or classical piano, you should check it out!

**Comment by hectorsector** [comment]
Great work @rbanton! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
