### ISSUE TITLE
Stephan Nears

### ISSUE THREAD

**Issue by StephanNears** [cop1000/cop1000#110]
Hey there! My name is Stephan Nears, I'm 5'6" and eager to learn programming. I have a great interest in all sorts of technology and such. I can only hope that I can learn all that I need to move forward. So excited!

**Comment by Javier-of-the-Rich-Port** [comment]
Nice to meet you Stephan, hopefully we both get alot out of this class

**Comment by hectorsector** [comment]
Hi @StephanNears welcome to the course. Tell us a little bit about you! What aspects of technology interest you? What do you want to do with your newfound knowledge?

**Comment by hectorsector** [comment]
Great work @StephanNears! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
