### ISSUE TITLE
Pierre

### ISSUE THREAD

**Issue by Snack-Pack** [cop1000/cop1000#111]
Hello My name is Pierre and I am taking this class to refresh what i now about Programming and to learn some new things.
![img_0003](https://cloud.githubusercontent.com/assets/22598820/19053365/b00612f6-8988-11e6-99b5-d45c9d495e57.JPG)

**Comment by hectorsector** [comment]
@Snack-Pack what kind of programming do you already know?

**Comment by hectorsector** [comment]
Great work @Snack-Pack! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
