### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by jenny0325** [cop1000/cop1000#112]
Hello everyone, My name is Jenny, hopefully I'm the only Jenny in this class so Mr. Alfaro will know who it is. I am taking this class because I'm majoring in computer science, however; I have no programming experience, therefore I need to learn the basics.

**Comment by Selia97** [comment]
Nice to meet you Jenny! Same here as well, gotta learn the basics before anything else.

**Comment by GoogleFox** [comment]
Welcome to the class Jenny! I hope to see you grow in this class and make great use of what you learn! I hope you can conquer your greatest challenges and be happy with the success you make in this class! I only have HTML5, CSS & some JS knowledge, but it is extremely fun when you get to do what you want with it! :) I am excited to learn along side with you!

**Comment by hectorsector** [comment]
Welcome to the class @jenny0325 -- what would you like to do you with a computer science degree?

**Comment by hectorsector** [comment]
Great work @jenny0325! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
