### ISSUE TITLE
Maria 

### ISSUE THREAD

**Issue by mariadodoll** [cop1000/cop1000#113]
# Hello classmates,

My name is Maria 
![mars3](https://cloud.githubusercontent.com/assets/22593618/19060266/8370fcf2-89b4-11e6-9d64-99864934d492.jpg),

 I am interested in this class because I feel that technology is quickly advancing and I would like to dedicate my knowledge and technical skills to continue to strive for improvement. My personal interest include fishing, travelling, and listening to music.

**Comment by PlusCode** [comment]
Hi Maria :)

**Comment by hectorsector** [comment]
Welcome to the class @mariadodoll! I, too, love visiting Epcot 😄

**Comment by hectorsector** [comment]
Great work @mariadodoll! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
