### ISSUE TITLE
Kartik Patel

### ISSUE THREAD

**Issue by kpatelbz** [cop1000/cop1000#114]
Hey guys, my name is Kartik. I change my degree from biology to computer science and this is my first computer class. So, I hope you guys don't get annoyed with me if I ask questions. I look forward to working with all of you. 
(https://cloud.githubusercontent.com/assets/22617088/19076060/5b2e5f62-8a15-11e6-920b-d57a3575b279.jpg)

**Comment by hectorsector** [comment]
Welcome to the course, @kpatelbz -- I think you'll find the rest of the students are very friendly. Ask away and feel free to answer others' questions yourself.

**Comment by hectorsector** [comment]
Great work @kpatelbz! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
