### ISSUE TITLE
Hello I'm GoogleFox.

### ISSUE THREAD

**Issue by GoogleFox** [cop1000/cop1000#115]
Hello everyone! My name is Kenny West. I use GoogleFox as my display name in almost everything. If you're interested in seeing what I look like, my GitHub profile picture is me. I am interested in this class because I love to do things on the computer and I am extremely interested in Game Design & Development. I love all the possibilities we can do with Game Design & Development and I want to see what kind of impact I can make in this world using it. I very much so love to play video games. I am very interested in survival or puzzle games. If you'd like to know anything else about me, feel free to ask!

**Comment by jlievano95** [comment]
I like video games too. Good job.

**Comment by jenny0325** [comment]
@GoogleFox Nice to meet you, with your skills I am sure you will have a great impact using what you'll learn.

**Comment by AGuerraDumas** [comment]
I love playing video games too, and I also want to learn to design games.

**Comment by hectorsector** [comment]
Welcome to the course, @GoogleFox! I took a few Game Design courses when I was at UF. I learned to appreciate the work that goes into designing a video game!

**Comment by hectorsector** [comment]
Great work @GoogleFox! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
