### ISSUE TITLE
James Lievano - Hello class

### ISSUE THREAD

**Issue by jlievano95** [cop1000/cop1000#116]
My name is James,  I am 21 years old. I'm majoring in Information Technology at Valencia College. My hobbies include video games, fishing, hiking, and playing guitar. I hope to graduate from Valencia so that I can continue at a University somewhere.

**Comment by hectorsector** [comment]
Welcome to the course @jlievano95! Have you been able to hike around Florida? It's such a flat place but I'm always keeping my 👀 open for opportunities.

**Comment by hectorsector** [comment]
Great work @jlievano95! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by jlievano95** [comment]
If your into mountains and hills then Florida is not a great place to hike. I like to photograph wildlife, that's mainly why I go hiking. I regularly find snakes, birds and alligators when I go. If you're into that then here's a site for some hiking trails: www.floridahikes.com

**Comment by hectorsector** [comment]
Oooh thanks for the link @jlievano95! I'll have to check it out. Spoiler alert! The first project will have you create a site -- maybe you can make it a place to host your photos or to blog about your hikes!
