### ISSUE TITLE
James Pryde Introduction

### ISSUE THREAD

**Issue by ClicheUsername** [cop1000/cop1000#117]
Hi everyone, my name is James. I am currently working as an IT Helpdesk rep at a small company based in Orlando. I've had a Github account for quite a while now so I just continued to use it for this course. The reason I'm interested in this course (and programming in general) is because I've always been interested in computers and how they work, and how you can just type text in to them and it will do exactly what you tell it to do. My career aspirations are to move up into a developer role at a company, and eventually to work as an independent game developer.

**Comment by hectorsector** [comment]
What a great username, @ClicheUsername! Welcome to the course -- it's a pleasure to learn a little bit about you.

**Comment by hectorsector** [comment]
Great work @ClicheUsername! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
