### ISSUE TITLE
Andyel Guerra

### ISSUE THREAD

**Issue by AGuerraDumas** [cop1000/cop1000#118]
Hello everyone, my name is Andyel Guerra, I have learn a little bit of Java and Html, I am looking forward to refreshing my knowledge of programming. I hope you all have a good time learning.

**Comment by Dukeiv** [comment]
Nice to meet you Andyel. Never really did Java but I have been interested in learning it. Maybe we can collaborate soon.

**Comment by hectorsector** [comment]
Welcome @AGuerraDumas! Have you used Java or JavaScript? The naming convention makes it complicated but they're pretty different.

**Comment by hectorsector** [comment]
Great work @AGuerraDumas! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
