### ISSUE TITLE
Dukeiv Seepersad

### ISSUE THREAD

**Issue by Dukeiv** [cop1000/cop1000#119]
Hey everyone my name is Dukeiv but everyone calls me Duke for short. I'm going for my A.S in Network Engineering with my main focus being Microsoft Administration and Cybersecurity. I Hope to learn some new things in this course.

**Comment by JBrady22** [comment]
Hi duke. Cybersecurity is a great field to go into because of all the application it has today. I am potentially looking to get it as a minor but not sure yet. I too hope to learn something new in this course and i hope we can do it together.

**Comment by hectorsector** [comment]
Welcome to the course, @Dukeiv! Networking is something that's always been challenging for me. I'm glad I took a few courses about it in grad school as it becomes relevant in the everyday world!

> I am potentially looking to get it as a minor but not sure yet.

@JBrady22 sometimes you have to take so many related classes for a major, that you might as well minor in something 😉. I wasn't an Electrical Engineer in school, but I took so many Electrical Engineering courses that I just took one extra class to get the minor.

**Comment by hectorsector** [comment]
Great work @Dukeiv! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
