### ISSUE TITLE
Jonathan C. Schelmety | Introduction

### ISSUE THREAD

**Issue by schell10** [cop1000/cop1000#12]
Hello,

My name is Jonathan Schelmety. I'm Originally from Bronx, New York.  I moved to Orlando when I was around 15.  I'm currently an IT Project Coordinator at Orlando Health.

I'm fascinated by the power for programming and hope to learn as much as I can about the basics.

Thank You
Jonathan C. Schelmety

**Comment by rbanton** [comment]
Wow, im from up north too. I was born in Canada and moved here as a kid.

**Comment by hectorsector** [comment]
It's great to meet you, @schell10! It sounds like you may have dome a bit of programming before -- have you played with any languages in particular?

**Comment by schell10** [comment]
I enjoy learning about python.  Is it possible to create 3d objects with python?

**Comment by hectorsector** [comment]
Great work @schell10! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.

**Comment by hectorsector** [comment]
> Is it possible to create 3d objects with python?

@schell10 I haven't done it myself, but a quick search led me to vpython, which seems to do what you want it to. I have used trinket.io which allows you to do some 2D art, perhaps it has some 3D packages as well.
