### ISSUE TITLE
Justin Brady

### ISSUE THREAD

**Issue by JBrady22** [cop1000/cop1000#120]
Hello my name is Justin Brady. I am interested in this class because i am going to get a degree in computer programming and analysis. Some personal interests of mine is gaming and movies as well as fishing and hunting.

**Comment by SBeauford** [comment]
Hey Justin I to enjoy gaming and movies and my degree is software engineering something pretty similar to your degree. Good luck to you and I look forward to working with you as a classmate this semester.

**Comment by hectorsector** [comment]
Welcome to the course, @JBrady22! What kind of video games do you like? I like strategy games and FPS.

**Comment by hectorsector** [comment]
Great work @JBrady22! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
