### ISSUE TITLE
Sidney Beauford

### ISSUE THREAD

**Issue by SBeauford** [cop1000/cop1000#121]
Hello everyone, 
 My name is Sidney you can call me Sid for short if you want. I'm taking this class because I am a software engineering major. I'm not quite sure what I want to do with my degree when I'm done with school yet but I'm hoping to figure it out along the way. A few things I like to do are play video games and watch football and I currently work as an event guide at universal.

**Comment by hectorsector** [comment]
It's great to meet you @SBeauford! What does an event guide do at Universal? I like going to the theme parks 🎢 so I'm always interested in finding out how the internals work.

**Comment by hectorsector** [comment]
Great work @SBeauford! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
