### ISSUE TITLE
JBrady22's Project 1 submission

### ISSUE THREAD

**Issue by JBrady22** [cop1000/cop1000#129]
Paste your web site's published URL here: https://JBrady22.github.io/

Check each of the following boxes to ensure you can score :100:
- [check ] Bootstrap is used.
- [check ] Web site contains images.
- [check ] Web site contains text.
- [check ] Web site contains external links.
- [check ] All of the web site's content can be accessed just by scrolling.
- [check ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [check ] The web site contains original content.
- [check ] The web site doesn't contain inappropriate content.
- [check ] The web site is published to GitHub Pages.
- [check ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@JBrady22 looks great! Although you start using bootstrap, the image doesn't properly resize when I resize the browser window. This is supposed to be one of the benefits of bootstrap. See if you can figure out how to make that work using what you learned on FreeCodeCamp. Doing this will ensure the following requirement is met:

> Bootstrap is used.

**Comment by JBrady22** [comment]
I went in and added the class img-responsive if that is what you meant. let me know if i need to fix this further. Thanks.

**Comment by hectorsector** [comment]
That did it. ✨ fantastic work 😄

**Comment by hectorsector** [comment]
Great work @JBrady22! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
