### ISSUE TITLE
I'm Christian Williams

### ISSUE THREAD

**Issue by Cjwilliams36** [cop1000/cop1000#13]
Hi, I'm Christian Williams. I am interested in this class because it is a requirement for my major which is Network Engineering. I have always been fascinated by computers and technology in general so hopefully programming will me be a fun new experience. 

(https://cloud.githubusercontent.com/assets/21317834/18064979/eb7240a2-6dff-11e6-9aad-114f3ab995d7.jpg)

**Comment by schell10** [comment]
Hey Christian.  This is also a requirement for me.  Looking forward to working with you.

**Comment by hectorsector** [comment]
It's great to learn a little bit about you, @Cjwilliams36! Programming is applicable to so many fields these days. I hope that you find some useful tidbits that you can apply to your everyday work 😄

**Comment by hectorsector** [comment]
Great work @Cjwilliams36! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
