### ISSUE TITLE
JS-Koans /about_objects

### ISSUE THREAD

**Issue by Cjwilliams36** [cop1000/cop1000#130]
@cop1000/professor
I am having trouble with the js-koans. I'm currently on about_objects but I can't seem to get the last question right.

**Original** 

```
test("adding functions", function() {
    var person = {
        name: "Amory Blaine",
        age: 102,
        toString: function() {
            return __; // HINT: use the 'this' keyword to refer to the person object.
        }
    };
    equal("I Amory Blaine am 102 years old", person.toString(), "what should the toString function be?");

```

**My attempt**

```
test("adding functions", function() {
    var person = {
        name: "Amory Blaine",
        age: 102,
        toString: function() {
            return "I "+this.name+" am "+this.age+" years old"; // HINT: use the 'this' keyword to refer to the person object.
        }
    };
    equal("I Amory Blaine am 102 years old", person.toString(), "what should the toString function be?");


```

It tells me that I am missing a period but when I add it the entire code gets an error.

**Comment by hectorsector** [comment]
👋 @Cjwilliams36 the [original code](https://github.com/cop1000/js-koans/blob/master/topics/about_objects.js#L42) seems to have a period -- did you forget that in your `return` statement?

**Comment by Cjwilliams36** [comment]
I noticed that the error I was getting was actually an error for the next question. #40 About Objects "global failure." It appears as though this is not in the script.

**Comment by hectorsector** [comment]
OK @Cjwilliams36 so do you still need help? By the way, this may or may not be related, but I made a few updates to the original code after I initially published the project, so make sure you grab the most recent updates by following [these instructions](https://github.com/cop1000/cop1000/issues/124#issuecomment-253983472).

**Comment by Cjwilliams36** [comment]
@cop1000/professor 
The updated code still appears to have the problem.

Here we see the last task in about objects "adding functions":
![capture](https://cloud.githubusercontent.com/assets/21317834/19462228/42449f58-94b9-11e6-945a-3b5b2b0aecf2.JPG)

But the js-koans html file is asking for about objects "global failure" which doesn't exist in the script:
![capture1](https://cloud.githubusercontent.com/assets/21317834/19462248/6b1bebe8-94b9-11e6-90dc-cd6754efd3b7.JPG)

**Comment by hectorsector** [comment]
@Cjwilliams36 have you refreshed the page? This is what I see when I run your code:

<img width="1048" alt="screen shot 2016-10-18 at 4 28 29 pm" src="https://cloud.githubusercontent.com/assets/16547949/19500205/f74d0c8c-954f-11e6-8f79-2fe0ebbf74ff.png">

**Comment by Cjwilliams36** [comment]
@cop1000/professor I have just committed the changes to my github. Please run it again and see if you get the error that I am.

**Comment by hectorsector** [comment]
I see it with your new updates @Cjwilliams36 but then when I followed the [instructions linked previously](https://github.com/cop1000/cop1000/issues/124#issuecomment-253983472) I don't see that error anymore.

**Comment by hectorsector** [comment]
@Cjwilliams36 did you get this all squared out? If so, you can close the issue.
