### ISSUE TITLE
Javier-of-the-Rich-Port Project 1 submission

### ISSUE THREAD

**Issue by Javier-of-the-Rich-Port** [cop1000/cop1000#132]
https://javier-of-the-rich-port.github.io/

Check each of the following boxes to ensure you can score :100:
- [X ] Bootstrap is used.
- [X ] Web site contains images.
- [X ] Web site contains text.
- [X ] Web site contains external links.
- [X ] All of the web site's content can be accessed just by scrolling.
- [X ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [X ] The web site contains original content.
- [X ] The web site doesn't contain inappropriate content.
- [X ] The web site is published to GitHub Pages.
- [X ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port good start, but please ensure you provide credit to the creator of the template.

Additionally, you started to meet the following requirement but it's not completely met: 
> - [ ] Bootstrap is used.

The reason it's not met is that your text overrides some of your images currently. Check that you're placing images and text in their proper containers. When you do it right, the text should never go on top of an image, and when I resize my browser window, your image should resize to fit my window accordingly.

**Comment by Javier-of-the-Rich-Port** [comment]
I added the responsive class to the images but I didn't use a template.

**Comment by hectorsector** [comment]
Looks fantastic 😄 great work @Javier-of-the-Rich-Port

**Comment by hectorsector** [comment]
Great work @Javier-of-the-Rich-Port! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
