### ISSUE TITLE
GoogleFox's Project 1 submission

### ISSUE THREAD

**Issue by GoogleFox** [cop1000/cop1000#133]
Paste your web site's published URL here: GoogleFox.github.io

Check each of the following boxes to ensure you can score :100:
- [+] Bootstrap is used.
- [+] Web site contains images.
- [+] Web site contains text.
- [+] Web site contains external links.
- [+] All of the web site's content can be accessed just by scrolling.
- [+] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [+] The web site contains original content.
- [+] The web site doesn't contain inappropriate content.
- [+] The web site is published to GitHub Pages.
- [+] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@GoogleFox try resizing your browser window, and notice that some of the text doesn't resize with the window. That's because it's not properly placed in the bootstrap grid. See if you can fix that so that this requirement counts as met:

> [+] Bootstrap is used.

**Comment by hectorsector** [comment]
Great work @GoogleFox! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
