### ISSUE TITLE
Problems publishing week 8 assignment

### ISSUE THREAD

**Issue by aalevane** [cop1000/cop1000#135]
I'm finished with my assignment and I'm trying to "Publish" it using Github Desktop and I keep getting this Authentication Failed error message. I am signed in, and have tried restarting the app as well as logging out/back in and changing my password. I'm not sure what the problem could be.

![screen shot 2016-10-19 at 2 15 24 pm](https://cloud.githubusercontent.com/assets/15223517/19531714/a6fb9bb0-9606-11e6-8a27-3bc4ce4cdc71.png)

**Comment by aalevane** [comment]
I still can't get this to work. There's no info on this error message on github.com, I tried posting on stackoverflow, I tried contacting github. Still waiting for responses. Also noticed that while my branch shows on Github Desktop, I cannot see my branch on github.com. So confused.

**Comment by DhvaniP** [comment]
I'm having the exact same problem :/

**Comment by hectorsector** [comment]
@aalevane @DhvaniP did you submit your GitHub username early on in the survey? Also check your [notifications](https://github.com/notifications) to ensure you've received the invitation to join the cop1000 organization.

**Comment by aalevane** [comment]
I was able to fix it, I just needed to accept the invite to the COP 1000 group. However now I realize I made a mess clicking too many buttons on Github Desktop and don't know how to go back to my initial commit. Anyone know how I can do this?

![screen shot 2016-10-20 at 6 04 57 pm](https://cloud.githubusercontent.com/assets/15223517/19579896/e3d6d014-96f0-11e6-9972-dde3c6bc96ce.png)

**Comment by aalevane** [comment]
I just had to "revert" back my last commit to solve that last issue. I successfully submitted my assignment now.

**Comment by robpb24** [comment]
@hectorsector I am having this same problem still. I performed the survey back in week 2 and just did it again now to be safe but I don't have any notifications on github for an invite to the COP1000 group. I feel like I accepted it a long time ago so maybe this isn't the issue? I am showing in my github account I am part of the "githubschool" and "cop1000" repository.

**Comment by hectorsector** [comment]
Wohoo! So glad it worked out for you all @aalevane @robpb24

**Comment by rbanton** [comment]
Hi all, im wondering if anyone would know why my clone/download button is not working.

**Comment by hectorsector** [comment]
Raymond, you may have some better luck by joining the class chat???<https://gitter.im/valencia-cop1000/Lobby> and asking there with screenshots of what you're seeing.

-Prof. Alfaro

________________________________
