### ISSUE TITLE
Clone/Downloading a Repository

### ISSUE THREAD

**Issue by rbanton** [cop1000/cop1000#137]
Hello class, this is Ray. It seems that i am having trouble copying a repository to github desktop, because whenever i hit the clone or download button nothing happens, even when i have github desktop open. Would anyone know if i am doing something wrong or if my computer/browser is incompatible with github?

**Comment by hectorsector** [comment]
@rbanton check out the conversation that's going on in #135 -- I'm going to close this issue as I think you're having the same problem they are but feel free to chime in on #135 if that still doesn't resolve it.
