### ISSUE TITLE
mariadodoll Project 1 submission

### ISSUE THREAD

**Issue by mariadodoll** [cop1000/cop1000#138]
mariadodoll.github.io

Check each of the following boxes to ensure you can score :100:
- [X ] Bootstrap is used.
- [X ] Web site contains images.
- [X ] Web site contains text.
- [X ] Web site contains external links.
- [X ] All of the web site's content can be accessed just by scrolling.
- [X] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [X ] The web site contains original content.
- [X ] The web site doesn't contain inappropriate content.
- [X ] The web site is published to GitHub Pages.
- [X ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@mariadodoll here's a couple of things you can do that might help:

- the repository you'll use has to be named `yourusername.github.io`
- your content should be in a file called `index.html` in your repository
- when you've correctly done this, you can navigate to `yourusername.github.io` and you should see your web page, and you should be able to check these things work

**Comment by hectorsector** [comment]
Great work @mariadodoll! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
