### ISSUE TITLE
Keanu Zeng

### ISSUE THREAD

**Issue by kzeng16** [cop1000/cop1000#14]
Hi, my name is Keanu. I'm taking this class just to see what programming is like and to learn new things. I spend most of my time playing video games on the PC. I hope we can all get along.

**Comment by JacobDanger** [comment]
_"Honey, you've got a big storm coming"_

![hqdefault](https://cloud.githubusercontent.com/assets/21322254/18072241/92d268a2-6e2a-11e6-8179-d7bae9a66fe0.jpg)

**Comment by Jordan-Hosein** [comment]
@JacobDanger 
xD

**Comment by nshort1** [comment]
Hi, Keanu. A fellow PC gamer! Yes! What games do you play? I took the summer off and picked up the Left 4 Dead series for 5$ during a steam sale. I also just recently beat Borderlands 2. I was so adamant on not picking up any more games but Steam sales make it dangerously easy. I still find myself replaying L4D nonstop, though!

**Comment by hectorsector** [comment]
@kzeng16 I, too, want to know what kind of 🎮 you play -- don't leave us hanging!

> I was so adamant on not picking up any more games but Steam sales make it dangerously easy.

Agreed, @nshort1 it's way too easy!

**Comment by kzeng16** [comment]
I play CS:GO most of the time, but I've been playing Fallout 4 since they released the new dlc. I also play Total War: Warhammer and some Overwatch. I haven't beat borderlands 2 yet. I always get distracted by other games.

**Comment by hectorsector** [comment]
Don't hate me for saying this but... I have Fallout 4 for the Xbox and have played it a grand total of 30 minutes.

**Comment by hectorsector** [comment]
Great work @kzeng16! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
