### ISSUE TITLE
Selia97 Project 1 submission

### ISSUE THREAD

**Issue by Selia97** [cop1000/cop1000#140]
https://selia97.github.io/.github.io/index.html

Check each of the following boxes to ensure you can score :100:
- [x ] Bootstrap is used.
- [x ] Web site contains images.
- [ x] Web site contains text.
- [ x] Web site contains external links.
- [ x] All of the web site's content can be accessed just by scrolling.
- [ x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ x] The web site contains original content.
- [ x] The web site doesn't contain inappropriate content.
- [x ] The web site is published to GitHub Pages.
- [ x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@Selia97 please make sure you follow the instructions for how to get your project up on GitHub -- the link you provided is to a file on your machine and I do not have ways to access that unless it's published.

**Comment by hectorsector** [comment]
Great work @Selia97! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
