### ISSUE TITLE
jmedian90's Project 1 submission

### ISSUE THREAD

**Issue by jmedian90** [cop1000/cop1000#141]
Paste your web site's published URL here: 

Check each of the following boxes to ensure you can score :100:
https://jmedian90.github.io
- [:check:] Bootstrap is used.
- [:check: ] Web site contains images.
- [:check: ] Web site contains text.
- [:check: ] Web site contains external links.
- [:check: ] All of the web site's content can be accessed just by scrolling.
- [:check: ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [:check: ] The web site contains original content.
- [:check: ] The web site doesn't contain inappropriate content.
- [:check: ] The web site is published to GitHub Pages.
- [:check: ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Looks great, @jmedian90

**Comment by hectorsector** [comment]
Great work @jmedian90! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
