### ISSUE TITLE
aarvizu's Project 1 submission

### ISSUE THREAD

**Issue by aarvizu** [cop1000/cop1000#147]
Paste your web site's published URL here: https://aarvizu.github.io/aarvizu/

Check each of the following boxes to ensure you can score :100:
- [x ] Bootstrap is used.
- [x ] Web site contains images.
- [x ] Web site contains text.
- [x] Web site contains external links.
- [x ] All of the web site's content can be accessed just by scrolling.
- [ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x ] The web site contains original content.
- [x ] The web site doesn't contain inappropriate content.
- [x ] The web site is published to GitHub Pages.
- [ ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Great start, @aarvizu. If you'd like your website to be accessible at simply `aarvizu.github.io`, then just rename your repository to `aarvizu.github.io`. 

Please ensure that the site meets the following criteria:

> Users can navigate to different sections of the webpage by clicking buttons in the navigation.

**Comment by hectorsector** [comment]
Great work @aarvizu! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
