### ISSUE TITLE
Dhvani Patel

### ISSUE THREAD

**Issue by DhvaniP** [cop1000/cop1000#15]
Hey everyone, 
My name is Dhvani. I was born in India but moved to Florida at the age of 7. Ever since I was a kid, I've always been interested in exploring new things. For instance, I'd be playing piano one minute and then learning now to knit the next. I guess you could say I'm all over the place. I do, however, spend most of my free time playing games on my ps3 or reading random philosophical articles. Part of the reason I took this class is to figure myself out and see if this could potentially be something of my interest.

**Comment by Jordan-Hosein** [comment]
Hello Dhvani! What games do you play on the PS3? Hope you'll enjoy the class!

**Comment by KaidyCEThomas** [comment]
Hello Dhvani,

I'm all over the place too...I want to learn everything. Know anything about Japanese Philosophy? 

Best luck with COP 1000!

**Comment by marxspawn** [comment]
Hello Dhvani, my name is ray. I noticed the last name Patel and I am curious if you happened to be related to an Amish Patel? Only reason I ask is my father worked with him for the Orange County Government here in orlando for a while. Either way good luck and a pleasure to meet you

**Comment by DhvaniP** [comment]
@Jordan-Hosein I've got a ton of games, more than half of them have just been lying there though haha. I typically just play Uncharted 3, Cod waw zombies, or Gta V.

**Comment by DhvaniP** [comment]
@KaidyCEThomas Thats awesome! And a bit- not nearly as much as I'd like to. Thank you :) Best of luck to you as well.

**Comment by DhvaniP** [comment]
@marxspawn Hahah No, sorry, I don't think I am. The thing is, there's billions of people with my last name but I'm not exactly related to each one of them. Its sorta like the common name Smith. Good luck, pleasure to meet you as well!

**Comment by hectorsector** [comment]
It's great to meet you, @DhvaniP! It's always fun when people join this class to learn something new even if it's not required.

**Comment by hectorsector** [comment]
Great work @DhvaniP! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
