### ISSUE TITLE
VComney JS-Koans Project

### ISSUE THREAD

**Issue by vcomney** [cop1000/cop1000#150]
I will try to submit this in the correct format, if I need to. I was in a time crunch and dealing with computer issues all at the same time. My apologies for any delay this causes. I just wanted to at least show the work before the deadline.

module("About Arrays (topics/about_arrays.js)");

test("array literal syntax and indexing", function() {
    var favouriteThings = ["cellar door", 42, true]; // note that array elements do not have to be of the same type
    equal("cellar door", favouriteThings[0], 'what is in the first position of the array?');
    equal("42", favouriteThings[1], 'what is in the second position of the array?');
    equal("true", favouriteThings[2], 'what is in the third position of the array?');
});

test("array type", function() {
    equal("object", typeof([]), 'what is the type of an array?');
});

test("length", function() {
    var collection = ['a','b','c'];
    equal(3, collection.length, 'what is the length of the collection array?');
});

test("stack methods", function() {
    var stack = [];
    stack.push("first");
    stack.push("second");

```
equal("second", stack.pop(), 'what will be the first value popped off the stack?');
equal("first", stack.pop(), 'what will be the second value popped off the stack?');
```

});

test("queue methods", function() {
    var queue = [];
    queue.push("first");
    queue.push("second");
    queue.unshift("third");

```
equal("third", queue.shift(), 'what will be shifted out first?');
equal("first", queue.shift(), 'what will be shifted out second?');
```

});

module("About Asserts (topics/about_asserts.js)");

test("ok", function() {
    ok(true === true, 'what will satisfy the ok assertion?');
});

test("not ok", function() {
    ok(false === false, 'what is a false value?');
});

test("equal", function() {
    equal(2, 1 + 1, 'what will satisfy the equal assertion?');
});

module("About Assignment (topics/about_assignment.js)");

var temp = 5;

test("local variables", function() {
    var temp = 1;
    equal(temp, 1, "Assign a value to the variable temp");
});

test("global variables", function() {
    temp = 1; // Not using var is an example. Always use var in practise.
    equal(1, window.temp, 'global variables are assigned to the window object');
});

module("About Control Structures (topics/about_control_structures.js)");

test("if", function() {
    var isPositive = false;
    if (2 > 0) {
        isPositive = true;
    }
    equal(true, isPositive,  'what is the value of isPositive?');
});

test("for", function() {
    var counter = 10;
    for (var i = 1; i <= 3; i++) {
        counter = counter + i;
    }
    equal(16, counter, 'what is the value of counter?');
});

test("for in", function() {
    // this syntax will be explained in about objects
    var person = {
        name: "Amory Blaine",
        age: 102
    };
    var result = "";
    // for in enumerates the property names of an object
    for (var property_name in person) {
        result = result + property_name;
    }
    equal("nameage", result, 'what is the value of result?');
});

test("ternary operator", function() {
    var fruit = true ? "apple" : "orange";
    equal(apple, fruit, 'what is the value of fruit?');

```
fruit = false ? "apple" : "orange";
equal(orange, fruit, 'now what is the value of fruit?');
```

});

test("switch", function() {
    var result = 0;
    switch (2) {
        case 1:
            result = 1;
            break;
        case 1+1:
            result = 2;
            break;
    }
    equal(2, result, 'what is the value of result?');
});

test("switch default case", function() {
    var result = "Pippin";
    switch ("m") {
        case "f":
            result = "Frodo";
            break;
        case "s":
            result = "Samwise";
                break;
        default:
            result = "Merry";
            break;
    }
    equal("Merry", result, 'what is the value of result?');
});

test("null coalescing", function() {
    var result = null || "a value";
    equal("a value", result, 'what is the value of result?');
});

module("About Equality (topics/about_equality.js)");

test("numeric equality", function() {
    equal(3 + 4,  7, "");
});

test("string equality", function() {
    equal("3" + _"7", "37", "concatenate the strings");
});

test("equality without type coercion", function() {
    ok(3 === 3, 'what is exactly equal to 3?');
});

test("equality with type coercion", function() {
    ok(3 == "3", 'what string is equal to 3, with type coercion?');
});

test("string literals", function() {
    equal("frankenstein", "frankenstein", "quote types are interchangable, but must match.");
    equal('frankenstein', 'frankenstein', "quote types can use both single and double quotes.");
});

module("About Functions And Closure (topics/about_functions_and_closure.js)");

test("defining functions directly", function() {
    var result = "a";
    function changeResult() {
        // the ability to access a variables defined in the same scope as the function is known as 'closure'
        result = "b";
    };
    changeResult();
    equal("b", result, 'what is the value of result?');
});

test("assigning functions to variables", function() {
    var triple = function(input) {
        return input \* 3;
    };
    equal(12, triple(4), 'what is triple 4?');
});

test("self invoking functions", function() {
    var publicValue = "shared";

```
// self invoking functions are used to provide scoping and to alias variables
(function(pv) {
    var secretValue = "password";
    equal("shared", pv, 'what is the value of pv?');
    equal("string", typeof(secretValue), "is secretValue available in this context?");
    equal("string", typeof(publicValue), "is publicValue available in this context?");
})(publicValue);

equal("undefined", typeof(secretValue), "is secretValue available in this context?");
equal("string", typeof(publicValue), "is publicValue available in this context?");
```

});

test("arguments array", function() {
    var add = function() {
        var total = 0;
        for(var i = 0; i < arguments.length; i++) {
            // complete the implementation of this method so that it returns the sum of its arguments
            // __

```
};


equal(undefined, add(1,2,3,4,5), "add 1,2,3,4,5");
equal(undefined, add(4,7,-2), "add 4,7,-2");
```

});

module("About Numbers (topics/about_numbers.js)");

test("types", function() {
    var typeOfIntegers = typeof(6);
    var typeOfFloats = typeof(3.14159);
    equal(true, typeOfIntegers === typeOfFloats, 'are ints and floats the same type?');
    equal("number", typeOfIntegers, 'what is the javascript numeric type?');
    equal(1, 1.0, 'what is a integer number equivalent to 1.0?');
});

test("NaN", function() {
    var resultOfFailedOperations = 7/'apple';
    equal(true, isNaN(resultOfFailedOperations), 'what will satisfy the equals assertion?');
    equal(false, resultOfFailedOperations == NaN, 'is NaN == NaN?');
});

module("About Objects (topics/about_objects.js)");

test("object type", function() {
    var empty_object = {};
    equal("object", typeof(empty_object), 'what is the type of an object?');
});

test("object literal notation", function() {
    var person = {
        **:**,
        **:**
    name: "Amory Blaine",
    age: "102"
  };
    equal("Amory Blaine", person.name, "what is the person's name?");
    equal(102, person.age, "what is the person's age?");
});

test("dynamically adding properties", function() {
    var person = {};
    person.name = "Amory Blaine";
    person.age = 102;
    equal("Amory Blaine", person.name, "what is the person's name?");
    equal(102, person.age, "what is the person's age?");
});

test("adding properties from strings", function() {
    var person = {};
    person["name"] = "Amory Blaine";
    person["age"] = 102;
    equal("Amory Blaine", person.name, "what is the person's name?");
    equal(102, person.age, "what is the person's age?");
});

test("adding functions", function() {
    var person = {
        name: "Amory Blaine",
        age: 102,
        toString: function() {
            return 102;  // HINT: use the 'this' keyword to refer to the person object.
        }
    };
    equal("I Amory Blaine am 102 years old.", person.toString(), "what should the toString function be?");
});

module("About Operators (topics/about_operators.js)");

test("addition", function() {
  var result = 0;
  //starting i at 0, add i to result and increment i by 1 until i is equal to 5
  for (var i = 0; i <= 5; i++) {
    result = result + i;
  }
  equal(15, result, "What is the value of result?");
});

test("assignment addition", function() {
  var result = 0;
  for (var i = 0; i <=5; i++) {
    //the code below is just like saying result = result + i; but is more concise
    result += i;
  }
  equal(15, result, "What is the value of result?");
});

test("subtraction", function() {
  var result = 5;
  for (var i = 0; i <= 2; i++) {
    result = result - i;
  }
  equal(2, result, "What is the value of result?");
});

test("assignment subtraction", function() {
  var result = 5;
  for (var i = 0; i <= 2; i++) {
    result -= i;
  }
  equal(2, result, "What is the value of result?");
});

//Assignment operators are available for multiplication and division as well
//let's do one more, the modulo operator, used for showing division remainder

test("modulus", function() {
  var result = 10;
  var x = 5;
  //again this is exactly the same as result = result % x
  result %= x;
  equal(0, result, "What is the value of result?");
});

module("About Strings (topics/about_strings.js)");

test("delimiters", function() {
    var singleQuotedString = 'apple';
    var doubleQuotedString = "apple";
    equal(true, singleQuotedString === doubleQuotedString, 'are the two strings equal?');
});

test("concatenation", function() {
    var fruit = "apple";
    var dish = "pie";
    equal("apple pie", fruit + " " + dish, 'what is the value of fruit + " " + dish?');
});

test("character Type", function() {
    var characterType = typeof("Amory".charAt(1)); // typeof will be explained in about reflection
    equal("string", characterType, 'Javascript has no character type');
});

test("escape character", function() {
    var stringWithAnEscapedCharacter  = "\u0041pple";
    equal("apple", stringWithAnEscapedCharacter, 'what  is the value of stringWithAnEscapedCharacter?');
});

test("string.length", function() {
    var fruit = "apple";
    equal(5, fruit.length, 'what is the value of fruit.length?');
});

test("slice", function() {
    var fruit = "apple pie";
    equal("apple", fruit.slice(0,5), 'what is the value of fruit.slice(0,5)?');
});

module("About this (topics/about_this.js)");

test("'this' inside a method", function () {
    var person = {
        name: 'bob',
        intro: function () {
            return "Hello, my name is " + this.__;
        }
    }
    equal(person.intro(), "Hello, my name is bob", "If an object has a method can you access properties inside it?");
});

test("'this' on unattached function", function () {
    var person = {
        globalName: 'bob',
        intro: function () {
            return "Hello, my name is " + this.globalName;
        }
    }

```
var alias = person.intro;
```

module("About Truthyness (topics/about_truthyness.js)");

test("truthyness of positive numbers", function() {
    var oneIsTruthy = 1 ? true : false;
    equal(true, oneIsTruthy, 'is one truthy?');
});

test("truthyness of negative numbers", function() {
    var negativeOneIsTruthy = -1 ? true : false;
    equal(true, negativeOneIsTruthy, 'is -1 truthy?');
});

test("truthyness of zero", function() {
    var zeroIsTruthy = 0 ? true : false;
    equal(false, zeroIsTruthy, 'is 0 truthy?');
});

test("truthyness of null", function() {
    var nullIsTruthy = null ? true : false;
    equal(false, nullIsTruthy, 'is null truthy?');
});

**Comment by hectorsector** [comment]
@vcomney I am closing this, please feel free to submit via the [`js-koans` repository](https://github.com/cop1000/js-koans).
