### ISSUE TITLE
ClicheUsername's Project 1 submission

### ISSUE THREAD

**Issue by ClicheUsername** [cop1000/cop1000#152]
Paste your web site's published URL here: https://clicheusername.github.io/

Check each of the following boxes to ensure you can score :100:
- [✔] Bootstrap is used.
- [✔] Web site contains images.
- [✔] Web site contains text.
- [✔] Web site contains external links.
- [✔] All of the web site's content can be accessed just by scrolling.
- [✔] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [✔] The web site contains original content.
- [✔] The web site doesn't contain inappropriate content.
- [✔] The web site is published to GitHub Pages.
- [✔] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
I loved that this was the beginning of a resume, @ClicheUsername! Fantastic work. 

If you'd like to explore further, there are some beautiful resume templates out there in Jekyll, that might be a natural next step for your site:
- https://github.com/jglovier/resume-template
- https://github.com/biomadeira/vitae
- https://github.com/philipithomas/jekyll-resume

**Comment by hectorsector** [comment]
Great work @ClicheUsername! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
