### ISSUE TITLE
Hello all 

### ISSUE THREAD

**Issue by PlusCode** [cop1000/cop1000#156]
Getting a script error working with the js Koans project here are a few pix of the error 

 
![koans error2](https://cloud.githubusercontent.com/assets/21061664/19893089/51bb09fc-a01e-11e6-9342-659042b966b2.jpg)

![koans error 3](https://cloud.githubusercontent.com/assets/21061664/19893105/5d084bc6-a01e-11e6-88e2-eac59e65767d.jpg)

And if I click the "rerun" I get this; 
 
![koans error](https://cloud.githubusercontent.com/assets/21061664/19893109/65e889e0-a01e-11e6-9a16-d8832204f78a.jpg)
 
I keep trying to "backup" what I've got done and that doesn't work either :(

**Comment by marxspawn** [comment]
Try comparing the original arrays file to the file you are debugging. Compare from [cop1000/js-koans/topics](https://github.com/cop1000/js-koans/tree/master/topics). To know you are working with the original codes, then one by one, enter the fix and run the code.

I would accidentally changing my branch, and found this route helpful. Let me know if you have already done this and I'll see where else I may be able to help

**Comment by marxspawn** [comment]
I should have elaborated, check the full code for accidental changes, not just the fixes entered by yourself. Hope this helps

**Comment by hectorsector** [comment]
@PlusCode check out ☝️ @marxspawn's suggestions above... can you link us to your code, too? We should be able to help by looking at it, too.

**Comment by marxspawn** [comment]
Any luck with completing this test?

**Comment by PlusCode** [comment]
Well I deleted everything on my computer: Github desktop and all the files. re-installed everything and I was able to complete the assignment, now I get an error when I try to sync the files. I need someone with write access to delete merge request to the master #31

**Comment by hectorsector** [comment]
@PlusCode I've closed https://github.com/cop1000/js-koans/pull/31 but I don't think that'll help -- what are you struggling with so I can help you move past it?

**Comment by PlusCode** [comment]
I still can't sync my desktop with github 
![sync problem](https://cloud.githubusercontent.com/assets/21061664/20117536/105204d2-a5cf-11e6-8183-51ea7141c864.jpg)

**Comment by hectorsector** [comment]
@PlusCode could you record the steps you're taking and post it here? You can [download LICEcap](http://www.cockos.com/licecap/) to save the recording as a GIF.

**Comment by PlusCode** [comment]
![js koans](https://cloud.githubusercontent.com/assets/21061664/20156789/e17d35ce-a69f-11e6-959a-e8bb5da459a1.gif)

**Comment by PlusCode** [comment]
hectorsector  I can zip the completed assignment and send it to you?

**Comment by hectorsector** [comment]
Yes please go ahead and do that in this case. Thanks.

**Comment by marxspawn** [comment]
@hectorsector Could the fact that the .gitattribute file is absent from this collaboration have anything to do with the build not reading his codes correctly?

**Comment by hectorsector** [comment]
@PlusCode I'm closing this as it is an inactive issue but please reopen if there's anything else we can do to help.
