### ISSUE TITLE
error cloning js koans

### ISSUE THREAD

**Issue by jmedian90** [cop1000/cop1000#157]
i attempted to clone the project js-koans and got the error message 
![image](https://cloud.githubusercontent.com/assets/22597719/19904311/752ce2be-a048-11e6-8f58-904978367560.png)
"failed to clone the repository 'cop1000/js-koans"
not exactly sure what to do here

**Comment by hectorsector** [comment]
@jmedian90 I noticed you're not a member of our Organization on GitHub. Did you complete the survey during first week of class that asks you to enter your GitHub username?

You'll be able to clone now that I fixed an issue we were having (see https://github.com/cop1000/js-koans/issues/20 if you're interested in reading about it) but you still won't be able to push it up to GitHub until you do add your name to the survey. Let me know when you do so on this issue.

**Comment by hectorsector** [comment]
I meant Week 2, here's the link: https://github.com/cop1000/cop1000/tree/master/week-2#to-do-list

**Comment by JBrady22** [comment]
I did the survey from week 2 and i am pretty sure i am part of the organization.  But i keep getting this message when trying publish my branch.
![capture 3](https://cloud.githubusercontent.com/assets/22639015/19934039/c571ab8a-a0eb-11e6-9744-b81f142a93a5.PNG)

**Comment by hectorsector** [comment]
👋 I've invited anyone that may have been missing as a collaborator. If your username is shown below, you'll have to accept an invitation which was sent to your email.

Students in Full Term class @cop1000/crn-14520:
@aarvizu
@anajera
@atompkins0
@ifresh102
@JacobDanger
@jesserivera
@SPierre30

Students in full-term class @cop1000/crn-14315:
@AAR0NPI3RC3
@cristivela1217
@emerced2
@forharambe
@ftorrado2016
@gaponte6
@Jomarm92x
@Lolivo
@rthompson73
@Sami287
@tiagaloppe

Students in late-start class @cop1000/crn-14415:
@AGuerraDumas
@bbutner1
@claytonhiggs
@Dukeiv
@Hkhan15
@JBrady22
@jenny0325
@jlievano
@jmedian90
@kpatelbz
@mariadodoll
@Nuridean
@SBeauford

**Comment by JacobDanger** [comment]
I saw this on both gitter and my email, but I'm not sure what I'm supposed to click on. Clicking on my name just brings me to my profile. Is there a separate email I should be looking for?

**Comment by hectorsector** [comment]
@JacobDanger here's what the invitation email should look like. Click on the button to accept. You'll know it will have worked when you see a badge next to your name in your comments.

<img width="667" alt="screen shot 2016-11-02 at 12 15 55 pm" src="https://cloud.githubusercontent.com/assets/16547949/19937154/75963990-a0f6-11e6-9f2f-85ee4a54256a.png">

<img width="807" alt="screen shot 2016-11-02 at 12 17 57 pm" src="https://cloud.githubusercontent.com/assets/16547949/19937158/796de1c6-a0f6-11e6-96cb-5a32a09f6586.png">

**Comment by JacobDanger** [comment]
Unless what I need is in the email you sent detailing all the names, I haven't gotten another email with the invitation

**Comment by hectorsector** [comment]
@JacobDanger your email may have been sent a while ago, but you should still be able to accept the invitation by going directly to https://github.com/cop1000 see if there's a banner there near the top for you to accept

**Comment by JacobDanger** [comment]
Man it's like you work here or something. Thanks!
