### ISSUE TITLE
Kaidy Ellis - Introduction-Discussion

### ISSUE THREAD

**Issue by KaidyCEThomas** [cop1000/cop1000#16]
Hello!

My name is Kaidy-Ann Ellis and I'm originally from Jamaica. I've been working in the hospitality industry for about 10 years but looking forward to something new and challenging! I got excited about programming a few month ago and found that it is something I would love to learn more of and possibly turn into a career. In my spare time I love going to the beach (as I mentioned I'm from Jamaica--island girl for life lol), painting and anything that has to do with art.

Best of luck to you all with COP 1000 and hope to learn something from each of you.

- Kaidy

**Comment by tiagaloppe** [comment]
Hello Kaidy. It's really awesome that you're trying out something new. I am also trying this class out. I have always been interested in programming, but I never took the initiative to try it. I hope we have a great semester.

**Comment by hectorsector** [comment]
Welcome to the course @KaidyCEThomas! I'm wondering what got you thinking about programming? For me, it's always been something that I've taken an interest in so I always wonder how someone stumbles upon it as an adult.

**Comment by KaidyCEThomas** [comment]
@hectorsector I literally clicked on a web ad out of curiosity. It was Frozen themed, lol! Somewhat juvenile but I was so intrigued I signed up on Code Academy, started networking with the IT department at my job. And ultimately found this to be the next best challenge for me.

**Comment by KaidyCEThomas** [comment]
@tiagaloppe I hope you have a great semester as well! Who knows where this journey will lead; to spectacular things I hope. Enjoy the ride my friend.

**Comment by hectorsector** [comment]
Great work @KaidyCEThomas! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
