### ISSUE TITLE
Hi, my name is Jacob

### ISSUE THREAD

**Issue by JacobDanger** [cop1000/cop1000#17]
Hello! My name is Jacob, and I'm interested in programming because I enjoy forming an idea and slowly molding it into something tactile that works. I've had a vested interest in computers since high school, along with science and astronomy, classic nerd stuff. Buzzwords are an important part of my vocabulary- fake it til' you make it.

**Comment by hectorsector** [comment]
It's great to learn a bit about you, @JacobDanger! It sounds like you've tried programming before, amirite? Any particular languages?

**Comment by JacobDanger** [comment]
Most recently I've been practicing with Java, but prior to that I've tested the waters with Lua. Like learning and actual language, it's usually easier if you have a mentor to prod you in the right direction. So I'm excited to see what this course has to offer!

**Comment by hectorsector** [comment]
Great work @JacobDanger! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
