### ISSUE TITLE
Tia

### ISSUE THREAD

**Issue by tiagaloppe** [cop1000/cop1000#18]
Hi, everyone. My name is Tia I am 25 years old and I am from Orlando, FL. I moved here from Long Island New York about 3 years ago with my girlfriend. I am graduating this semester with my AA. I will then be moving on  to get my bachelors in human resources. I currently work at Target as a price change team member and I am signed off to be a Team Lead, just waiting for a store to be re-located to. In my spare time, I like to go to the parks nearby. I go to Disney World all the time and I like going to Universal as well, my favorite park to go to is Sea World, I like to see all the animals. I am excited to take this class I am very interested in computer work.

**Comment by hectorsector** [comment]
It's great to meet you, @tiagaloppe! It seems a lot of my friends have moved here from Long Island -- did you grow up there?

**Comment by hectorsector** [comment]
Great work @tiagaloppe! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
