### ISSUE TITLE
Michael Dean

### ISSUE THREAD

**Issue by mdean19** [cop1000/cop1000#19]
Hey everyone, I'm Michael. Born and raised in Orlando, have never been farther North than Jacksonville. I'm taking this class because it's a required course in my major, Network Engineering Tech. I'm a reader and a gamer (both video games and tabletop!). I hope to learn everything I can in this course and pass it with an A.

**Comment by lminks** [comment]
I think you're one of the first people I've heard of that isn't much of a traveler. Everyone I know has been out of state a bunch and seems to love traveling. It's probably fair to assume we're both in the "never seen snow" club.

**Comment by hectorsector** [comment]
Traveling is fun; I highly recommend seeing ❄️, @mdean19 @lminks 😉 

Welcome to the course, @mdean19! I like board games a lot -- have you played _Love Letter_? I believe there's quite a few variations of it, but it's very simple and fun.

**Comment by mdean19** [comment]
@hectorsector I've played the Batman version of it, friend told me the original is better though. I like playing Munchkin, haha. So simple yet so fun to backstab your friends.

**Comment by hectorsector** [comment]
Great work @mdean19! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
