### ISSUE TITLE
Hello! - Jordan Hosein

### ISSUE THREAD

**Issue by Jordan-Hosein** [cop1000/cop1000#2]
Hello! My name's Jordan, I'm excited to start this class and hope to become good friends with everyone in the class. I'm currently a high school senior and am taking this class to help get me on track with my major at other colleges. I like video games (and can talk about some games for days), space sciences, physics, the military (3rd generation military brat), and diving. I love to travel, see new things, and meet new people. 
Have a great day!

**Comment by MCastro46** [comment]
Good morning Jordan!
what type of games are you interested in? and Space sciences as in astronomy or  aeronautics?

**Comment by Jordan-Hosein** [comment]
Morning Castro!
Mainly RPGs and FPS, but I enjoy playing almost everything (except sports). 
Astrophysics, actually!

**Comment by hectorsector** [comment]
It's great to learn a little bit about you, @Jordan-Hosein! I like FPS as well. I've started to play *No Man's Sky* -- I know it's gotten a lot of criticism but I'm enjoying it. Have you tried it?

**Comment by Jordan-Hosein** [comment]
Yes! I absolutely love the game even though it's getting a lot of bad reviews. I do have to agree that the inventory size is a little too small though.

**Comment by kzeng16** [comment]
Hi, Jordan. What would you say your all time favorite games are?

**Comment by Jordan-Hosein** [comment]
@kzeng16
Undertale
Pokemon
Mass Effect Trilogy (still have to finish it)
Fallout 3 & New Vegas 
Battlefield 4
BO2
No Man's Sky
Final Fantasy XIV

**Comment by MCastro46** [comment]
What server do you play on for xiv? :0

**Comment by Jordan-Hosein** [comment]
@MCastro46
You play FFXIV!? I haven't played in a couple months cause of the whole subscription thing and me being broke. But I'm on Siren, I think I can make more new accounts on different servers still.

**Comment by MCastro46** [comment]
I do yeah!  I'm on byrnhilder I started again last night after being off a few months looking forward to the new end-game content lol

**Comment by MCastro46** [comment]
I do yeah!  I'm on byrnhilder I started again last night after being off a few months looking forward to the new end-game content lol

**Comment by Jordan-Hosein** [comment]
@MCastro46 
Awesome! You play on PC or console?

**Comment by MCastro46** [comment]
@jordan-hosein I'm mostly on pc now, but Ive played on both

**Comment by Jordan-Hosein** [comment]
@MCastro46
I play on PS3 for FFXIV

**Comment by Jordan-Hosein** [comment]
@MCastro46
Although I think it's cross platform and can work with people on PC also

**Comment by MCastro46** [comment]
@Jordan-Hosein  Yeah correct it is cross-platform so if you ever go back let me know!

**Comment by hectorsector** [comment]
Great work @Jordan-Hosein! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
