### ISSUE TITLE
Hi my name is Jomar Marquez!

### ISSUE THREAD

**Issue by Jomarm92x** [cop1000/cop1000#20]
I am in my 3rd semester in Valencia and going strong to finish next year. I love technology and am expanding my knowledge as best as I can between general IT to Networking Security and, one of my personal favorites, Computer Programming. Looking forward to another great semester and to have interesting programming projects with my fellow classmates here!

**Comment by hectorsector** [comment]
It's great to meet you, @Jomarm92x! Have you programmed before? If so, what language have you used?

**Comment by Jomarm92x** [comment]
Likewise @hectorsector , and in High School I had a programming class and it was pretty bare bones. I learned Just Basic, Visual Basic, Java, C++, and Flash. As extensive as I'd like to be in those languages, I was only given, as mentioned before, a bare bones approach to all of these aside from the occasional project. I honestly LOVED programming and now that I am here I feel that this could be my expansion from my networking major to maybe a programming one.

**Comment by hectorsector** [comment]
Awesome, @Jomarm92x ❤️

**Comment by hectorsector** [comment]
Great work @Jomarm92x! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
