### ISSUE TITLE
Hi there! I'm Art.

### ISSUE THREAD

**Issue by aalevane** [cop1000/cop1000#21]
Hi all! My name is Art. While this class is required for my Computer Programming A.S. degree, I'm actually looking forward to it. I want to be a web developer and I need to learn Javascript which I'm excited to start familiarizing myself with. In my spare time I like learning new skills and spending time with my dogs.

**Comment by Mikedaris94** [comment]
Hey Art! I'm Mike nice to meet you, I too am interested in what this class has to offer i extend a goodluck to you and hope you enjoy the course!

**Comment by aleallopez** [comment]
hi, art ,love your name , nice to meet you

**Comment by aalevane** [comment]
@aleallopez Thanks, Agnes! Nice to meet you too. It's actually short for Artemis. I've been getting a lot of compliments on it lately, not sure why all of a sudden, you're like the 3rd person this week lol. Good luck!

**Comment by hectorsector** [comment]
Welcome, @aalevane! I think you'll enjoy the class taught in JavaScript then. Front-end development has come incredibly far and I hope when the course is over your mind will be blown with all the possibilities available to you.

**Comment by hectorsector** [comment]
Great work @aalevane! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
