### ISSUE TITLE
Mike Daris

### ISSUE THREAD

**Issue by Mikedaris94** [cop1000/cop1000#22]
Hello everyone! I'm from west palm beach and I moved to Orlando for school this is my last course at Valencia. I'm interested in this course because I want to build an understanding of programming and see if it's something I want to pursue career in it.

**Comment by aalevane** [comment]
Hey Mike! How are you liking Orlando? Are you looking to transfer to a university after Valencia?

**Comment by Mikedaris94** [comment]
Yes I love orlando and yes ucf hopefully.

**Comment by anajera** [comment]
Hi, nice to meet you! I also want to pursue a career in programming. What do you like about Orlando?

**Comment by Mikedaris94** [comment]
It's very different from West Palm Beach.

**Comment by hectorsector** [comment]
It's great to meet you, @Mikedaris94! Programming can be very fun, but also very challenging and time consuming. I applaud 👏 you for trying it out in the form of a course.

**Comment by hectorsector** [comment]
Great work @Mikedaris94! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
