### ISSUE TITLE
Milena

### ISSUE THREAD

**Issue by mirenagreen** [cop1000/cop1000#23]
Hello there,

My name is Milena and I'm originally from Japan/Brazil. I just moved to Florida a month ago from Connecticut and I'm still getting used to this place. I enjoy sunshine, Disney and not having snow anymore. This is my third semester in college and also it is my first programming class. I am very excited to learn more about coding to know if I'll enjoy a career in technology.
Hope to work with all of you soon!

**Comment by orlandogivens** [comment]
Milena, 

Nice to meet you. This is also my first programming class and I want to learn as much as possible also. Look forward to working with you.

**Comment by Lolivo** [comment]
Hello Milena,, I know it must be quite the change from the snowy north to the sunshine state, I'm originally from Venezuela and still getting used to Florida, I hope we learn alot of things from this class!

**Comment by ftorrado2016** [comment]
Hey Milena. What Part of Brazil did you live in? I went to Japan for a week in a vacation when I was younger in around 2004-2005, it was really fun! Its fun to meet fellow Brazilians! :)

**Comment by hectorsector** [comment]
It's great to meet you, @mirenagreen! I enjoy the theme parks also. Do you have a favorite park? It's always been Hollywood Studios for me.

**Comment by jesserivera** [comment]
Hey Milena, and welcome. It is my current dream and goal to take a trip to Japan, I have always been very intrigued by the culture and lifestyle there, also I am a JDM car fanatic so making it out there to check out the car scene has always been at the top of my list!

**Comment by Zaquonya** [comment]
Hi Milena, I moved from NY a few years ago so I understand what you mean about the snow. This is also my first programming course. Good luck with the class and I'm excited to work with you.

**Comment by mirenagreen** [comment]
Hi @orlandogivens nice to meet you too! Hope we both enjoy this class:D

**Comment by mirenagreen** [comment]
Hi @Lolivo nice to meet you! Indeed Florida is quite different from Connecticut. I guess for the first time in my life I will have a warm winter! Can't wait for it ;)

**Comment by mirenagreen** [comment]
Hi @ftorrado2016  I was born  in Cuiaba, MT, but moved to Japan when I was a baby so I didn't really lived in Brazil. Which part of Japan did you visit?? I am happy you like it!!Looking forward to working with you!!

**Comment by mirenagreen** [comment]
Hello Professor @hectorsector , nice to meet you too!! It's a tough decision to choose my favorite park. I love all of them!

**Comment by mirenagreen** [comment]
Hi @jesserivera, I hope you can visit Japan one day. It's an amazing and beautiful country. I am sure you will love it!! I am not a fan of JDM car but I have some friends that love it! I am looking forward to working with you!!

**Comment by mirenagreen** [comment]
Hi @ZPeterson2 nice to meet you!! Which part of New York are you from? It's a relief I won't have to deal with the freezing and cold winter for a while. I hope we have a great class throughout this semester. Looking forward to working with you!!

**Comment by ZPeterson2** [comment]
@mirenagreen I'm from Long Island, Hempstead specifically. I'm sure the class will be great.

**Comment by hectorsector** [comment]
Great work @mirenagreen! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
