### ISSUE TITLE
Orlando 

### ISSUE THREAD

**Issue by orlandogivens** [cop1000/cop1000#24]
Hello Class, 

My name is Orlando. I'm originally from South Carolina. I was in the military for 6 years and have recently moved to Orlando Jan 2016. I have a one year old son. My major is cyber security. I heard that programming is hard so this is something that I want to learn as much as I can.

**Comment by lazybray** [comment]
Hi Orlando, hope you've been having a good time since you moved down to Florida. Thanks for supporting our country as well, always nice to see dedicated people coming back home safe. I'm not that experienced as well, but I hope we can both learn as much as possible. Sincerely, Brayden.

**Comment by Lolivo** [comment]
Hello! I hope Florida has been good to you, I hope we both learn alot!

**Comment by mdean19** [comment]
Welcome to Florida! Thank you for your service, Orlando. Programming isn't too hard, just have to remember a lot of things, aha.

**Comment by hectorsector** [comment]
Welcome @orlandogivens and thanks for your service. Programming requires that one's very detail oriented and think through difficult problems, but there's an amazing rush that comes out of solving the problems so if it's in your personality to work on something until you get it, I think you'll enjoy it 😄

**Comment by hectorsector** [comment]
Great work @orlandogivens! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
