### ISSUE TITLE
Brayden Burgett

### ISSUE THREAD

**Issue by lazybray** [cop1000/cop1000#25]
Hello, I am Brayden Burgett. I'm 19, My major is Computer Science. I enjoy playing Pokemon Go, various computer games, watching bad horror movies, and sleeping. I used to do some programming back in High School, but I'm overall fairly new. Hope to have a relaxed year programming.

**Comment by anajera** [comment]
Hi, its nice to meet you. I also a lot of programming back in high school. I hope you enjoy the class.

**Comment by DhvaniP** [comment]
Hey Brayden, I enjoy sleeping and watching horribly hilarious horror movies as well! I've yet to play Pokemon Go though. I wish you the best of luck! :)

**Comment by mdean19** [comment]
Bad horror movies are always fun to watch. They turn into comedies.

**Comment by hectorsector** [comment]
Welcome @lazybray! I know your handle has the word "lazy" in it but... 

> Hope to have a relaxed year programming.

I hope it won't be *too* relaxed 😉

**Comment by hectorsector** [comment]
Great work @lazybray! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
