### ISSUE TITLE
Intro Discussion - Alex

### ISSUE THREAD

**Issue by anajera** [cop1000/cop1000#26]
Good morning, my name is Alex and this is my second semester at Valencia. I am interested in this class because i want to get a Computer Science degree and i have loved to program since i was in 9th grade. My personal interests are developing android/iOS apps and websites, I am also familiar with .NET and SQL Server. I also like shooting wildlife photography and spending time at the beach.

**Comment by Sami287** [comment]
Hello Alex. I am Samantha, but you can call me Sami.  I also want to get my computer science degree and started programming my 9th grade year. I also like photography and going to the beach, so we should get along well. Good luck this year!!

**Comment by hectorsector** [comment]
Welcome, @anajera it's great to meet you. Shoot me an email and let's talk about your programming experience. I want to make sure this is the right class for you.

**Comment by hectorsector** [comment]
@anajera I no longer see you on my class roll so I'm closing this issue but please reopen if there's some sort of mistake.
