### ISSUE TITLE
Luis Romero-Olivo

### ISSUE THREAD

**Issue by Lolivo** [cop1000/cop1000#27]
Hello! My name is Luis, I came from Venezuela 4 years ago, I just graduated from Saint Cloud this year.I work part time at Give Kids The World. I want to transfer to UCF for their computer science program while minoring in actuarian science. I love a wide variety of things,mostly video games, sports, reading and lifting. I'm really looking forward to learn how to code and make cool stuff.

**Comment by hectorsector** [comment]
Welcome, @Lolivo! What sort of video games do you like? I like to read, too. I'm looking for some fiction to get into next, as I've been reading lots of nonfiction lately 😢

**Comment by Lolivo** [comment]
Thank you @hectorsector I mostly play online games on steam like rust or CSGO, usually with my friends. I love indie titles too I'm always on ghe lookout for hidden gems and one or another single player game. Have you heard of a book called Gravity's rainbow by Pynchon? The author was in the Navy and then became a physicist, he writes fiction that borders on non fiction and is filled with conspiracy theories but it is an amazing read, I'd recommend it.

**Comment by hectorsector** [comment]
That sounds interesting, @Lolivo. Reminds me of Neal Stephenson. I like the ideas behind Stephenson's books but his vocabulary is over the top.

**Comment by hectorsector** [comment]
Great work @Lolivo! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
