### ISSUE TITLE
Salvador Ruiz

### ISSUE THREAD

**Issue by SalvadorRuizIII** [cop1000/cop1000#28]
Hello All! To begin, I look forward to an awesome semester with you. Currently, I'm actually away on travel in Thailand until the end of October. Before my recent travels however, I was working as a paramedic in an urgent care in Orlando. As of now, I've got interest in pursuing a bachelors in information management with a focus in IT forensics; which is why I've chosen to take this course. As of now I have no programming experience, however hope to learn soon!

**Comment by marxspawn** [comment]
Pleasure to meet you Salvador,

My name is Ray. I am going for my AS in computer programming and will be attending this class with you for the fall term. Thailand seems like a amazing place to visit, I myself have never ventured outside the states.

Good luck to you on your Travels as well as in the IT Forensics field 
:+1:

**Comment by hectorsector** [comment]
@SalvadorRuizIII welcome! I hope you'll share some great 📷 with us!

**Comment by hectorsector** [comment]
Great work @SalvadorRuizIII! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
