### ISSUE TITLE
Ray Anderson

### ISSUE THREAD

**Issue by marxspawn** [cop1000/cop1000#29]
#  :wave: **Hello World** :wave:

My name is Ray and I am 39 years old :older_man: currently enrolled as a freshman at Valencia for my Associates in Science for Computer Programming. I have lived in Florida my whole life growing up over on the west coast in the Bradenton/Sarasota area. Since graduating High School (21 years ago :confounded:) I have worked as a residential/commercial electrician for almost 20 years. I enjoyed the work :zap::boom::fire: but not the weather :sunny::rage::sweat_drops: So i am making a career change for myself as well as my family :family: I am married and have 3 beautiful girls and 1 giant nerdy son (absolutely no idea where he gets that from). I have always enjoyed learning new things, and programming (boring as it may sound to most) fascinates me and I am eager get started on this new venture in my life. I love to joke around and have good time (when an appropriate time is available :ok_hand: :wink:). I do look forward to this class and working with everyone this term.
## Opinions wanted ##
- [x] :+1: I laughed, I cried 
- [ ] :-1: Back to the drawing board

**Comment by aalevane** [comment]
Hey Ray I'm also a freshman for an A.S. in Computer Programming! Do you know yet exactly where you want to take your programming? Personally I'm going for web development.

**Comment by marxspawn** [comment]
Possibly android development, but I plan on getting a better understanding of the course and seeing where it takes me.

Good luck @aalevane

**Comment by vcomney** [comment]
I'm glad I'm not the only older guy here with all of these youngsters, lol. It's definitely a brave leap, but the heat of the Florida sun is enough to make anyone jump out of the pan. I spent many years working outside doing underground utilities. So I totally understand. Good luck.

**Comment by radicalpharaoh** [comment]
Good job, Ray on the drive and focus you got to go back and learn even after 20 plus years. My dad is an electrian as well and he voices the same complaints as you, the weather and the labor are quite hard on him sometimes so I can see where you are coming from. Hope everything goes well in this class for you and you can create a great career out of this.

**Comment by hectorsector** [comment]
It sounds like you have a fantastic family, @marxspawn! It's great to learn a little bit about you and I hope this class will help you decide where to take your fantastic talent.

**Comment by SPierre30** [comment]
Blah lol. I was trying to find the emoji's on this thing for my thread xD. It's nice to meet you Ray.

**Comment by hectorsector** [comment]
Great work @marxspawn! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
