### ISSUE TITLE
Magdiel Castro

### ISSUE THREAD

**Issue by MCastro46** [cop1000/cop1000#3]
Good morning my name is Magdiel, 23 year old student from Kissimmee. I'm relatively new at coding and look forward to learning a lot.I personally do enjoy Gaming (PC and console), as well as going out on adventures. I look forward to working with you all!

**Comment by AntoineDS** [comment]
Hello Magdiel welcome!

**Comment by Jordan-Hosein** [comment]
Morning Magdiel! 
I play on console and PC as well! Although I don't have any of the next-gen consoles yet. Saving up for one while I debate over PS4 or XO

**Comment by rbowser5** [comment]
Hey! I just built a PC for gaming! It's awesome. Currently addicted to Overwatch.

**Comment by Jordan-Hosein** [comment]
"Oversalt"

**Comment by hectorsector** [comment]
Welcome @MCastro46! Don't hesitate to include a picture of yourself on [your profile](https://github.com/settings/profile) if you're comfortable. 

What consoles do you own or do you enjoy? I play on the PS4 usually, but every now and then I dust off the Xbox also!

**Comment by Cjwilliams36** [comment]
Hello Magdiel, I'm also into PC gaming but I also have an xbox one for the exclusives. PC Master Race

**Comment by aleallopez** [comment]
Hi magdiel!!

**Comment by MCastro46** [comment]
@Cjwilliams36  PC master race indeed lol, any games specifically you play?

**Comment by Cjwilliams36** [comment]
I am more of a casual gamer so I've played Life Is Strange (my favorite so far), Portal 1 and 2 (duhhhh), and all the Bioshock games. I do tend to play a round of LoL every once in a while.

**Comment by hectorsector** [comment]
Portal is my all-time favorite game, @Cjwilliams36!

**Comment by hectorsector** [comment]
Great work @MCastro46! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
