### ISSUE TITLE
Luke Minks

### ISSUE THREAD

**Issue by lminks** [cop1000/cop1000#30]
Hello! I guess I'm a little late to the party, even though the class has only been open for a day. I don't have much experience with programming (or github) yet, but I'll need to have an understanding of it before too long since I am planning to go into electrical engineering. I hope this class goes well for everyone.

**Comment by hectorsector** [comment]
Welcome @lminks! I have a minor in Electrical Engineering -- but I never really wanted one. When I was studying computer engineering I just took so many darn electrical courses that I figured I might as well do it!

**Comment by hectorsector** [comment]
Great work @lminks! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
