### ISSUE TITLE
Hey I'm Cristina

### ISSUE THREAD

**Issue by cristivela1217** [cop1000/cop1000#32]
Hey I'm Cristina,
I'm a dual enrollment student at Valencia and I am currently a Junior in High school. I am not very familiar with programming now but am definitely interested in learning. I plan on studying Mechanical Engineering, and that is mainly why I registered for this class. I am looking forward to learning and getting the hang of programming during this semester.

**Comment by marxspawn** [comment]
Congratulations, even if if you decide this isn't for you it is definitely something to add to a resume in the future. I myself have wrote some small codes growing up (on computers most kids today probably never heard of) but drifted off of it as I got older. Most of what I see today looks similar but with a completely new style.
Good luck in class and life :v:

**Comment by hectorsector** [comment]
Welcome @cristivela1217! All the engineering disciplines are challenging, but hopefully programming will give you an extra tool in your arsenal that you can use to tackle all the problems!

**Comment by jriosrodriguez** [comment]
Hey!! We are both in Dual Enrollment student, Juniors, and interested in Mechanical Engineering! Good stuff!

**Comment by hectorsector** [comment]
Great work @cristivela1217! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
