### ISSUE TITLE
Hey! I'm Samantha Coleman

### ISSUE THREAD

**Issue by Sami287** [cop1000/cop1000#33]
Hello class!  I am Samantha Coleman, but people call me Sami.  I am 17 years old and doing dual enrollment from West Orange High School.  I am part of the senior class of 2017 and I am extremely ﻿﻿﻿﻿﻿﻿excited to be done with high school.  I started Valencia last year while I was a junior, so this is my 3rd semester taking college classes.  I want to finish my A.A at Valencia then hopefully go to UCF to get my computer science degree.  I love building robots and coding websites (I know I'm a nerd).  I am also a big dog person.  I have five dogs that are my life and I treat them as if they are my children.  I wish everyone luck this semester!! I know we can do it!!!

**Comment by anajera** [comment]
Hi, my name is Alex. I wanted to learn to build robots and even joined the club, but decided to learn how to code instead. I like building websites as well however, more specifically I like to develop android/iOS apps. I am also a dog person, I have an Italian greyhound I got as a rescue and i also want to go to UCF for my Computer Science Degree.

**Comment by hectorsector** [comment]
It's great to learn a bit about you @Sami287! Send me an email -- I want to make sure that this is the right class for you with the programming experience you've described.

**Comment by hectorsector** [comment]
Great work @Sami287! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
