### ISSUE TITLE
Robert Thompson

### ISSUE THREAD

**Issue by rthompson73** [cop1000/cop1000#34]
Hello! My name is Robert, I am 16 and a dual enrollment student currently a junior at West Orange High School.  I am taking this class because I have always loved technology and computers and want to further my knowledge.  I also play classical guitar and have been for about 6 years.  I love dogs and recently adopted a puppy from the rescue I volunteer at.  I hope everyone has a good semester!

**Comment by hectorsector** [comment]
It's good to meet you, @rthompson73! I like 🐕 as well and I hope to get one in a few months. How's the pup doing? Chewing up everything?

**Comment by hectorsector** [comment]
Great work @rthompson73! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
