### ISSUE TITLE
Samuel Pierre

### ISSUE THREAD

**Issue by SPierre30** [cop1000/cop1000#35]
Hey there everyone. My name is Samuel Pierre. I'm planning to put up a picture soon so I apologize if I don't have one yet. I first started off as an Engineering Major and switched to computer science a semester or two back, hopefully I've chosen the right path ^_^. Hope to work with all of you soon. Oh and if anything interesting about myself, um I work as a security officer at Universal Studios o-o.

**Comment by jmasterson5** [comment]
That's cool What do you hope to be doing once you have graduated from valencia

**Comment by hectorsector** [comment]
Welcome, @SPierre30! What brought you to computer science over engineering?

**Comment by SPierre30** [comment]
Ha, just how long it'd take me to finish and all the extra math on top of all the math xD. I'm still planning to finish it later but I'd like to at least do this one first.

**Comment by SPierre30** [comment]
![image](https://cloud.githubusercontent.com/assets/21351228/18145419/2497b9b2-6f99-11e6-9f90-c977c2e4df5a.png)

**Comment by marxspawn** [comment]
@SPierre30 :eyes:

**Comment by hectorsector** [comment]
Great work @SPierre30! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
