### ISSUE TITLE
Julian Masterson

### ISSUE THREAD

**Issue by jmasterson5** [cop1000/cop1000#36]
I'm interested in this class because I'd like to go into video game development
My interest include playing video games, going hiking, and I also like to go on cruises I've been on almost 30 cruises in my life time
![image](https://cloud.githubusercontent.com/assets/21342128/18113617/4e66b65c-6eff-11e6-91c7-9aba68d7352f.png)

**Comment by hectorsector** [comment]
😮 that's a lot of cruises @jmasterson5! Do you have a favorite cruise line? Welcome, by the way.

**Comment by hectorsector** [comment]
Great work @jmasterson5! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
