### ISSUE TITLE
Felipe Torrado

### ISSUE THREAD

**Issue by ftorrado2016** [cop1000/cop1000#37]
Hey guys, whats up! 
My Name is Felipe Torrado and right now I'm too lazy to get a picture of myself therefore you can deal with this puppy I found online. Same thing right?

I'm brazilian, moved to the USA in 2008, going for a computer engineering degree (hopefully), still figuring out what I want to do with life though, after college what road to take. 
I'm 19 years old, and I work at Best Buy. I really like my job, and it allows me to keep up to date (up to a certain amount) with current technology. I know LUA and basic HTMl5, I'm here to learn more. 

Right now I'm getting ready to spend a week in Massachusetts for my Cousin's wedding, which is the prime time for college classes to have started. Yay. I'm estatic as you can see.  /sarcasm

**Comment by hectorsector** [comment]
Welcome, @ftorrado2016! The timing of classes starting is always interesting. This is a pretty busy week for me, too, but I've enjoyed learning about y'all a lot. Enjoy Massachusetts!

**Comment by hectorsector** [comment]
Great work @ftorrado2016! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
