### ISSUE TITLE
Jose Pena

### ISSUE THREAD

**Issue by radicalpharaoh** [cop1000/cop1000#38]
Hello everyone! My name is Jose Pena. You can find a picture of me above this post. I'm taking this class as a pre-requisite and to help me learn what the basics of programming is. Since my major is in Information Technology, I hope this class creates a better confirmation that this career choice is the right one. Besides trying to do my best in Valencia, other interest I have is generally either watching shows like Steven Universe or Game of Thrones, listening to Death Grips or just lying around and being bored. Hope this class is as much an adventure as it is for you guys. Glad to spend this time with you all.

**Comment by Lolivo** [comment]
I'm an avid fan of Death Grips too, in fact I sent MC Ride an invitation to my graduation but he sadly wasn't able to make it.

**Comment by atompkins0** [comment]
Love watching Game of Thrones, just hate how it makes every other show feel so mediocre in comparison.

**Comment by hectorsector** [comment]
Welcome @radicalpharaoh! I appreciate your positive attitude and I hope this class helps you confirm your career choice.

**Comment by hectorsector** [comment]
Great work @radicalpharaoh! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
