### ISSUE TITLE
Hello from Antoine

### ISSUE THREAD

**Issue by AntoineDS** [cop1000/cop1000#4]
Hello everyone,

My name is Antoine(pronounced as Antwon), I'm one of your classmates and I am interested in this class to help increase my programming knowledge. I personally like  working, spending times with my girlfriend, Japanese cars(the ones that go BUWAHHHHHHH), and technology. 

That's me down there. I Hope everyone has an amazing time here.

![12592587_146220769106094_5248481543264344942_n](https://cloud.githubusercontent.com/assets/21311812/18053907/a195b886-6dcf-11e6-8717-9bc0eff8d807.jpg)

**Comment by Jordan-Hosein** [comment]
Hello Antoine, hope you have a great time as well!

**Comment by hectorsector** [comment]
Hello @AntoineDS! What interests you about technology? I like knowing how things work, and I'm addicted to that feeling you get when you tinker with something enough to get it to do what you want.

**Comment by AntoineDS** [comment]
@hectorsector the way we solve problems with technology and how we have no limit to what we can do with technology.

**Comment by hectorsector** [comment]
Great work @AntoineDS! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
