### ISSUE TITLE
Nathan Short

### ISSUE THREAD

**Issue by nshort1** [cop1000/cop1000#40]
Hi, all!

My name is Nathan Short. I'm 24 years old. I am a math major and this is my last class required to graduate with my degree from Valencia. Decided to take it easy this year and had the summer off and made this my last class for an easy (hopefully) winter. I plan on transferring to UCF to study Mechanical Engineering in the spring. I enjoy custom building computers and gaming (very few games these days lol), repairing cars, and riding my two motorcycles with my friends. I've worked the last 5 years at Disney's water parks as a Deepwater Lifeguard/Coordinator and even met my fiancée at Typhoon Lagoon!

Overall, I really hope to gain a basic understanding of coding from this course. I've dabbled with HTML more than 12 years ago when Neopets was a thing. I've also installed custom ROMS (Cyanogenmod) on my Android devices and I enjoy the idea of being able to tinker with things more.
![13576801_849786695166090_6205708961892308952_o](https://cloud.githubusercontent.com/assets/21367408/18140211/822b50dc-6f82-11e6-9e24-8c63a0a7ce13.jpg)

**Comment by AAR0NPI3RC3** [comment]
Welcome aboard! Good luck at UCF.

**Comment by hectorsector** [comment]
It's great to meet you, @nshort1! Neopets!? I remember that. Well, technology has come a long way 😉

**Comment by emerced2** [comment]
Nice to meet you Nathan. I was once too a deep water lifeguard at Disney World, primarily at Typhoon Lagoon but would cover resorts or Blizzard Beach if necessary. That was back in 2006 though, still cool to meet a fellow cast member.

**Comment by hectorsector** [comment]
Great work @nshort1! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
