### ISSUE TITLE
Aaron

### ISSUE THREAD

**Issue by AAR0NPI3RC3** [cop1000/cop1000#42]
Hi! My name is Aaron. I find this GitHub thing confusing. I have been interested in learning to code for many years, but found myself to lazy to do so. I am a newbie. I have very little experience with coding but I'm feeling ambitious.

**Comment by hectorsector** [comment]
Welcome, @AAR0NPI3RC3! I'm happy to help if any part of it seems confusing. Just holler.

**Comment by robpb24** [comment]
Hey Aaron, I've had the same interests and I'm in the newbie boat just like you but we all have to start somewhere! Good luck with the class, man.

**Comment by aarvizu** [comment]
I too am new to the programming stuff but lets hope that we can all get through this together. I look forward to working with you Aaron and you too Robert.

**Comment by AAR0NPI3RC3** [comment]
Thank you all for the warm welcome and for the wishes of good fortune. I hope this semester is a good one for us all!

**Comment by hectorsector** [comment]
Great work @AAR0NPI3RC3! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
