### ISSUE TITLE
JJ

### ISSUE THREAD

**Issue by jriosrodriguez** [cop1000/cop1000#43]
Good day,
My name is Joel (but you can call me JJ), I am Junior in High School, and part of the Dual Enrollment program with Valencia. I'm very interested in learning programming and all the possibilities it has; plus am interested in studying Engineering and I know programming would be an excellent skill for my future career. Undoubtedly, I'm excited about this class and I plan on learning the most I can from it.

**Comment by cristivela1217** [comment]
Hey JJ, I also am a dual enrollment student and am also planning on studying Engineering.

**Comment by hectorsector** [comment]
Welcome, @jriosrodriguez! What sort of work do you think you'd like to do when you've graduated?

**Comment by gaponte6** [comment]
Hey JJ! My family calls me JJ too haha! When I was in highschool I was in dual enrollment too, thats awesome that you're taking advantage of such a great opportunity.

**Comment by hectorsector** [comment]
Great work @jriosrodriguez! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
