### ISSUE TITLE
Jesse Rivera

### ISSUE THREAD

**Issue by jesserivera** [cop1000/cop1000#44]
Hello all, my name is Jesse Rivera. I am in the final stages of completing my AS in Network Engineering after a very long slow process. I currently work for an insurance brokerage company as a Desktop/Network Support Specialist. I have been working in IT for about 10 years now and hope to continue to grow in this industry and move up. I am originally from Milwaukee, WI and am a die hard Green Bay Packers fan. If there are any Chicago Bears fans here let me just apologize now because I know life must be difficult ;) Hope everyone enjoys the semester and good luck!

**Comment by hectorsector** [comment]
It's great to meet you @jesserivera. Going to school and working are difficult things to do, so 🎩 off to you for doing it!

**Comment by hectorsector** [comment]
@jesserivera I no longer see you on my class roll so I'm closing this issue but please reopen if there's some sort of mistake.

**Comment by jesserivera** [comment]
Hey Professor, I had to drop the class unfortunately because I received a message stating the class wasn't going to be covered by my financial aid. The course does show up as a requirement so I have to speak to someone in admissions about this. Hopefully I can take the class again with you next semester if all goes well.


Thank you again for everything.

________________________________
