### ISSUE TITLE
Jordan Yates

### ISSUE THREAD

**Issue by jjyates4** [cop1000/cop1000#45]
Hello everyone, my name is Jordan and I'm an 18 year old freshman at Valencia College. I was born here in Orlando, so I never really left.  My hobbies involve playing basketball and hanging out with friends in my free time. I consider myself a hardcore Lakers fan haha.  I chose this course because I think programming is fun and I'm majoring in Computer Science.

**Comment by forharambe** [comment]
Hey Jordan, I'm from Orlando also. Everyone tells me I should have played basketball because of how tall I am. I look forward to working with you in the class!

**Comment by hectorsector** [comment]
It's great to meet you, @jjyates4! I think Orlando is a great place to call 🏠

**Comment by hectorsector** [comment]
Great work @jjyates4! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
