### ISSUE TITLE
Zaquonya

### ISSUE THREAD

**Issue by ZPeterson2** [cop1000/cop1000#46]
Hi! My name is Zaquonya. I am a musician and started off as a music major at Valencia almost 2 years ago. I realized about a year ago that, although I love singing and making music, I would like to focus on making different programs and apps that others could use to create their music. I am taking this class to see if I would enjoy programming as a career. I haven't changed my Major to computer programming yet, but I'm hoping to at the end of this class.

**Comment by hectorsector** [comment]
Welcome, @ZPeterson2! You know, I know some musicians that are also programmers, it's not as odd as you might think. GitHub hosts a list of [🎶-themed repositories](https://github.com/showcases/music) that might interest you!

**Comment by ZPeterson2** [comment]
Thanks @hectorsector I will definitely look into those.

**Comment by hectorsector** [comment]
Great work @ZPeterson2! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
