### ISSUE TITLE
Announcements for Wed Aug 31-Mon Sep 5

### ISSUE THREAD

**Issue by hectorsector** [cop1000/cop1000#47]
Hi all! Here's a short video that I created to welcome you to the upcoming week. You can expect messages like this every week. Feel free to drop a comment here if you have any logistical questions or anything in the video was unclear.

📺: https://www.youtube.com/watch?v=PEpCePzVgtg

**Comment by aleallopez** [comment]
Is there any phone application to this web page? Because i do have my computer connected to my valencia mails , but not my phone ...

**Comment by aleallopez** [comment]
And is not that i want to do it but the phone won't let me put my valencia mail

**Comment by hectorsector** [comment]
@aleallopez you mean an app to access college emails? On iPhone I use either Outlook for mobile or can set it up right into Mail using an Exchange server. I'd imagine it's close to the same process on Android devices.

**Comment by aleallopez** [comment]
No i mean to the web page

**Comment by rbanton** [comment]
Cant wait to start programming, this is so hype :)

**Comment by hectorsector** [comment]
> No i mean to the web page

There's no official GitHub app, but there are a few out unofficial ones out there that access some of the same things you can do on GitHub.

**Comment by hectorsector** [comment]
This week has now completed. Next week's announcements will be at #59
