### ISSUE TITLE
Robert P

### ISSUE THREAD

**Issue by robpb24** [cop1000/cop1000#48]
Hey everyone, my name is Robert but everyone calls me Rob. I decided to take up computer programming in general because of my overall interest in computers. I spent a lot of my childhood in front of a screen so I figured why not give something a shot that I feel comfortable with. I've done some research and I'm not entirely sure exactly what I'm getting into but I'm excited to find out. Personally I'm a big sports guy, you name it I probably watch it but basketball is numero uno. I stay motivated to exercise every day but I'm a beach bum at heart. Can't wait to ride the wave with you all to a degree and hopefully a life changing career!
![21337771](https://cloud.githubusercontent.com/assets/21337771/18148653/fd138050-6fa8-11e6-9888-2254eefbeef2.jpg)

**Comment by hectorsector** [comment]
Welcome @robpb24! Let's make this class work for **you**. If you have any interests that you want to explore, let me know and I'll try to point out similarities or things you can look into to lead you in that direction. Programming has so many diverse applications that I'm sure you'll find your niche!

**Comment by hectorsector** [comment]
Great work @robpb24! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
