### ISSUE TITLE
Edwin Merced

### ISSUE THREAD

**Issue by emerced2** [cop1000/cop1000#49]
My name is Edwin Merced and I'm majoring in Computer Science. I enjoy playing video games, my girlfriend and I are currently hooked on a game called 7 days to die. I just recently started getting into cameras, I've got a collection of about 15 different cameras. I'm into the instant film more, so majority of my cameras are older. I was a Combat Medic in the United States Army for 5 years, got out and decided I no longer wanted to be in medicine, especially trauma. So my non tech savvy, prehistoric mind figured I would give computer programming a try. Because, why not? And here I am.

**Comment by aarvizu** [comment]
Hey there Edwin. 7 days to die huh? Well, i am also hooked on a game. It is a computer game though cause i am not sure if you play on console or computer. You should check this game out that i am currently hooked on Called DbD. And just a heads up programming deals with solving problems through reasoning. And its like dealing with typing out a language. So if you are good with those then i think you are a perfect fit for programming. Haha.

**Comment by hectorsector** [comment]
Welcome @emerced2. I think programming is such a diverse field that you might find the right cross-section with your interests 😉

**Comment by hectorsector** [comment]
Great work @emerced2! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
