### ISSUE TITLE
Ryan Bowser

### ISSUE THREAD

**Issue by rbowser5** [cop1000/cop1000#5]
Hey everyone! My name is Ryan Bowser. I'm working my way toward my articulated pre-major in Information Technology at UCF! I'm really interested in music and computer technology, as well as long walks on the beach, puppies, dancing all night long in the rain, etc. I'm looking forward to this semester!
![untitled-1](https://cloud.githubusercontent.com/assets/21312459/18055735/09b8f228-6dd7-11e6-936d-229bc1660db5.jpg)

**Comment by Jordan-Hosein** [comment]
Hello Ryan, nice to meet you!

**Comment by hectorsector** [comment]
Hi @rbowser5. Well, there's no more perfect thing in my book than cute puppies!

![](http://i.giphy.com/XuOOXWY29Y4z6.gif)

Do you like listening to music, or do you play an instrument also? I used to play the piano 🎹 when I was younger and I can't wait to start it up once again.

**Comment by vcomney** [comment]
Hey @rbowser5 what kind of music do you play?

**Comment by rbowser5** [comment]
I'm a bit of a jack-of-all-trades when it comes to music! My passion is drumming, but I also love to play guitar/bass/piano, as well as singing too loudly in the shower. I mostly play rock music, but also a fan of more modern pop/alternative stuff!

**Comment by hectorsector** [comment]
Great work @rbowser5! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
