### ISSUE TITLE
Introduction- Trevor

### ISSUE THREAD

**Issue by forharambe** [cop1000/cop1000#50]
Hey guys, my names Trevor. I am from Orlando and have lived here my entire life besides living in Gainesville for the past year. I'm in to cars and anything outdoors. I'm taking this class with the hopes of broadening my knowledge in computers. I can't wait to get started!

**Comment by jnorris18** [comment]
Whats up Trevor. I really like your account name. I myself am a huge supporter of Harambe, and believe he is a huge symbol to our generation. Good luck this semester, I know we'll both get A's for Harambe

**Comment by Lolivo** [comment]
Same here, I will succeed for Harambe too

**Comment by hectorsector** [comment]
Welcome, @forharambe. I ❤️ Gainesville -- it's where I went to school 🐊 How do you like it?

**Comment by hectorsector** [comment]
Great work @forharambe! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
