### ISSUE TITLE
John Norris

### ISSUE THREAD

**Issue by jnorris18** [cop1000/cop1000#51]
Hey class my names John. I am from Jupiter Florida and enjoy playing basketball and going out on the boat. Below is an attached picture of me and my favorite basketball player Kobe Bryant. ![185040364](https://cloud.githubusercontent.com/assets/21372629/18149777/4980c824-6fb0-11e6-8aac-188fce8c7a71.jpg)

I was interested in this class because I wanted to increase my computer skills.

**Comment by hectorsector** [comment]
😆 It's good to meet you, @jnorris18. What kind of skills would you like to increase or improve?

**Comment by hectorsector** [comment]
Great work @jnorris18! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
