### ISSUE TITLE
My name is Alexis Arvizu

### ISSUE THREAD

**Issue by aarvizu** [cop1000/cop1000#52]
Hello, just like my title states, my name is Alexis. I am 19 years old and I just moved to Orlando recently and i'm liking it so far. I am here for schooling purposes and the field i will be going into is computer science.

**Comment by hectorsector** [comment]
Welcome, @aarvizu. Where did you move from?

**Comment by ifresh102** [comment]
Hey @aarvizu Welcome to Florida! Hope you are enjoying the sunshine state so far, so much to do! Glad to hear we have more CS people in the class, best of luck to you this semester.

**Comment by aarvizu** [comment]
@hectorsector Sorry i'm responding late. I moved from West Palm. A 2 hour drive from here.

**Comment by hectorsector** [comment]
Great work @aarvizu! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
