### ISSUE TITLE
Floatie -- a $35 conference held in Downtown Orlando Oct 1-2

### ISSUE THREAD

**Issue by hectorsector** [cop1000/cop1000#54]
Hello everyone! I just came across [this conference](http://floatie.io) that'll be taking place right in our backyard. The registration fee is just $35 and includes housing (if you need it) as well as food throughout the conference.

**Comment by AntoineDS** [comment]
@hectorsector How do you find conferences like this?

**Comment by hectorsector** [comment]
I'm part of the Florida Hackers Facebook group. That's how I found this one :)




On Fri, Sep 9, 2016 at 8:11 AM -0700, "Antoine Stimphil" <notifications@github.com<mailto:notifications@github.com>> wrote:


@hectorsector<https://github.com/hectorsector> How do you find conferences like this?

-

**Comment by AntoineDS** [comment]
@hectorsector the team at Floatie says hey!!!!

**Comment by hectorsector** [comment]
:heart: so glad you could make it @AntoineDS! Share if you took some pictures :)

**Comment by hectorsector** [comment]
Closing this issue since this event has now passed. Check out [some pictures](https://www.facebook.com/floridahackers/photos/?tab=album&album_id=1119778048114518) from the event!
