### ISSUE TITLE
GitHub/Chatroom

### ISSUE THREAD

**Issue by KaidyCEThomas** [cop1000/cop1000#55]
@hectorsector 

 Hello Professor,

Hope you're well. I'm running into some issues when I attempt to join our chat room, I'm told I'm not a GitHub user, see screenshot below. Any help you can provide would be great. Thank you.

![image](https://cloud.githubusercontent.com/assets/21207842/18188604/76100fae-7081-11e6-9b6d-f909542a7bbc.png)

**Comment by hectorsector** [comment]
Were you able to get this resolved @KaidyCEThomas ?

**Comment by KaidyCEThomas** [comment]
Hi, 

I was able to resolve this, thank you! My only issue now is none of my computers will allow me to download Github Desktop. Not sure if it lack of space or program compatibility. I have windows 10 I believe so it should be compatible. Can you provide any help here?

Hope you had a great Labor Day weekend! Thanks again.

**Comment by hectorsector** [comment]
@KaidyCEThomas GitHub Desktop should be compatible with Windows 10. Are you getting in particular error messages or anything? You can drop the screenshots in this issue.

**Comment by hectorsector** [comment]
@KaidyCEThomas I'm going to go ahead and close this issue as you may have resolved it by now but if not feel free to reopen it.
