### ISSUE TITLE
Nathan Darley

### ISSUE THREAD

**Issue by Nathan801** [cop1000/cop1000#56]
Hello world! :P I am from Oviedo, Florida and I'm looking forward to getting my feet wet this semester learning some programming basics. I'm also looking forward to breaking keyboards due to semi-colons. Jokes aside i know a little C# and enjoy solving puzzles.

**Comment by SalvadorRuizIII** [comment]
Hello Nathan! I live in Oviedo As well, and am equally as excited about learning the basics of programming. I wish you the best in the course!

Regards,
Salvador Ruiz

**Comment by Nathan801** [comment]
Excellent. I was lucky enough to get the chance to play football with Blake Bortles years ago who happened to throw me the only touchdown i ever caught. Just a fun fact if you have any interest in football. Thank you for the reply Salvador.

**Comment by hectorsector** [comment]
Welcome @Nathan801! I haven't programmed in C# myself, but I hear it's an interesting language. Sounds like your interest line up well with the class. Enjoy!

**Comment by hectorsector** [comment]
Great work @Nathan801! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
