### ISSUE TITLE
Intro - Hamza Ali

### ISSUE THREAD

**Issue by ifresh102** [cop1000/cop1000#57]
Hey Everyone! My Name is Hamza Ali, usually go by Ali. Im taking this class for two reasons, one to actually get a formal introduction to programming and also take that knowledge to further my pursuit of a BS in IT. Other than being a tech geek:) I also am an avid watcher of football, Go Buccaneers! 

Best of luck to everyone this semester!

**Comment by hectorsector** [comment]
Welcome, @ifresh102! I ❤️ your avatar. Welcome to the course.

**Comment by hectorsector** [comment]
Great work @ifresh102! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
