### ISSUE TITLE
Dominic Mattingley

### ISSUE THREAD

**Issue by dmattingley1** [cop1000/cop1000#58]
Hello, my name is Dominic, but I go by Dom. I am taking this class as a stepping stone on my way to a BS in computer science. I have no formal practice in programming so I think this class will be a great place to start. As far as my hobbies go, I like competitive gaming and fitness.

Good luck to everyone this semester!

**Comment by hectorsector** [comment]
Welcome @dmattingley1! Competitive gaming, huh? What kind of gaming?

**Comment by dmattingley1** [comment]
@hectorsector  I attend tournaments for Super Smash Bros: Melee. It's an old game, but the community is constantly growing and it's pretty enjoyable as a spectator sport too.

**Comment by hectorsector** [comment]
Great work @dmattingley1! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
