### ISSUE TITLE
Alexander Tompkins

### ISSUE THREAD

**Issue by atompkins0** [cop1000/cop1000#6]
Hey, name is Alex, currently in my third year at Valencia and working towards my A.S. in Computer Programming. Half Korean, huge dog person, and honestly my biggest passion and what I enjoy doing most in life is playing video games, mainly PC gaming. Love discovering new music and have a bad habit of binge watching tv shows, with the occasional anime in between. Looking forward to working with you all and working towards graduating in the upcoming year.

**Comment by hectorsector** [comment]
It's great to meet you, @atompkins0! What sort of shows you do you like? I've recently been watching *Avatar: The Last Airbender*. I know it's old news to most people but it's new to me and I'm absolutely in love -- the best animated storytelling I've seen.

**Comment by hectorsector** [comment]
Great work @atompkins0! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
