### ISSUE TITLE
Announcements for Mon Sep 20-Sun Sep 25

### ISSUE THREAD

**Issue by hectorsector** [cop1000/cop1000#62]
A video introducing this week's topics has been published [on YouTube](http://youtu.be/xfW6l0hIp9Y).

Please use this issue to discuss any questions or comments as you work throughout this week. Happy coding!

**Comment by hectorsector** [comment]
@cop1000/all-students I've run my grading scripts again for the [week 2 assignments](https://github.com/cop1000/cop1000/tree/master/week-2#to-do-list) and grades were updated on Blackboard. If you still do not see a grade, please contact me via email so we can figure out what's going on.

It's important that you do this as I will start putting in zeros for unreceived assignments which will hurt your grade.

**Comment by ZPeterson2** [comment]
I dont have a grade for week 2.

**Comment by hectorsector** [comment]
@ZPeterson2 please contact me privately.

**Comment by hectorsector** [comment]
Closing this issue since the next announcement has been posted in #66
