### ISSUE TITLE
JacobDanger's Project 1 submission

### ISSUE THREAD

**Issue by JacobDanger** [cop1000/cop1000#63]
Paste your web site's published URL here: JacobDanger.github.io

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by rbowser5** [comment]
This was an important website for me.

**Comment by JacobDanger** [comment]
_I understand what the people want._

**Comment by hectorsector** [comment]
![](http://i.giphy.com/l0K3ZW5asxDbngG2c.gif)

**Comment by AntoineDS** [comment]
Nice!

**Comment by hectorsector** [comment]
@JacobDanger ✨ fantastic work! it looks like you created a Bootstrap equivalent from scratch, but remember that one requirement for this project is to use Bootstrap proper. You can find some [instructions over in FreeCodeCamp](https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers). Let me know if you have any questions about that. 

I have an additional suggestion (that won't cost you points, just to make your code better): consider resizing [this image](https://github.com/JacobDanger/JacobDanger.github.io/blob/master/index.html#L92) to speed up the time it takes for your site to load.

**Comment by hectorsector** [comment]
Great work @JacobDanger! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
