### ISSUE TITLE
Cjwilliams36 Project 1 submission

### ISSUE THREAD

**Issue by Cjwilliams36** [cop1000/cop1000#67]
Paste your web site's published URL here: Cjwilliams36.github.io

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
I ❤️ Portal @Cjwilliams36! Great choice.

My only suggestion here would be to ensure that you meet this criteria:

> - [ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.

**Comment by Cjwilliams36** [comment]
Does the back to top button not count?

**Comment by hectorsector** [comment]
@Cjwilliams36 Do you mean [this one](https://github.com/Cjwilliams36/Cjwilliams36.github.io/blob/master/index.html#L5)? If so, it points externally.

**Comment by Cjwilliams36** [comment]
I'm talking about this [this one](https://github.com/Cjwilliams36/Cjwilliams36.github.io/blob/master/index.html#L21rl)

**Comment by hectorsector** [comment]
Well, it's one button that does take you to the top, but see if you can figure out how to make a navigation bar that lets you jump to the different areas of your site.

**Comment by hectorsector** [comment]
Great work @Cjwilliams36! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
