### ISSUE TITLE
AntoineDS Project 1 submission

### ISSUE THREAD

**Issue by AntoineDS** [cop1000/cop1000#68]
Paste your web site's published URL here: https://antoineds.github.io/

I did use the Bootstrap template: http://startbootstrap.com/template-overviews/clean-blog/

credit to the creator of the template.

Check each of the following boxes to ensure you can score :100:

- [X] Bootstrap is used.
- [X] Web site contains images.
- [X] Web site contains text.
- [X] Web site contains external links.
- [X] All of the web site's content can be accessed just by scrolling.
- [X] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [X] The web site contains original content.
- [X] The web site doesn't contain inappropriate content.
- [X] The web site is published to GitHub Pages.
- [X] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Cool @AntoineDS!

Please make sure that the following criteria is met:

> All of the web site's content can be accessed just by scrolling.
> Users can navigate to different sections of the webpage by clicking buttons in the navigation.

A suggestion (that won't cost you points) might be to also think about the content of your site and ask yourself what you could do to make it more original. If it's meant to be like your own marketing material for Teslas, what if you took it in a different direction? Maybe you could 1up Tesla's web site 😉

**Comment by AntoineDS** [comment]
@hectorsector I know you highlighted that I didn't meet some of the criteria. Did you just wanted a single page setup that you scroll all the way down? I added some scrolling, was it too little scrolling? Are you not able to navigate to the About Tesla Page from the home page? 

Also I don't know how far I could go with Teslas information before it's copyright, because it's not my original idea. 

Please be as critical as you possibly can about my work. I definitely want to be better. 

Thank you, 

Antoine

**Comment by hectorsector** [comment]
@AntoineDS your site's content is split across multiple pages. The requirement is to have the content on one page, and the navigation bar should let you jump to different parts of the page. Does that make sense?

**Comment by AntoineDS** [comment]
@hectorsector so basically a scrolling landing page! Wow, I thought we needed multiple pages with access to different pages through the Nav Bar. Thank you professor.

**Comment by hectorsector** [comment]
Great work @AntoineDS! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
