### ISSUE TITLE
lminks Project 1 submission

### ISSUE THREAD

**Issue by lminks** [cop1000/cop1000#69]
Paste your web site's published URL here: https://lminks.github.io/

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Your site is just beautiful @lminks. Great work ❤️

**Comment by hectorsector** [comment]
Great work @lminks! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
