### ISSUE TITLE
Agnes

### ISSUE THREAD

**Issue by aleallopez** [cop1000/cop1000#7]
HI my name is agnes! I am from Puerto Rico currently studying in Valencia College in ,Orlando, this is my first time  doing a online class on my birthday to be exact ,  I am interested in this class because  i am in the field of computer programming and this will help me become a professional !

  
  ![img_0580](https://cloud.githubusercontent.com/assets/21309964/18057427/ee6ec612-6ddd-11e6-87d6-8d998c4dab35.JPG)

**Comment by hectorsector** [comment]
Welcome @aleallopez ... and Happy Birthday 🎉 🍰 

What sort of programming have you done previously?

**Comment by aleallopez** [comment]
I have never done it before actually this will be my first time🤗

**Comment by tylerch8** [comment]
Best of luck your new journey, Agnes! Some people have reservations about online classes but I personally like them. It allows you to be really flexible once you've become self-disciplined! And happy birthday!

**Comment by rbanton** [comment]
Good luck, i think it might be a little overwhelming at first but then easier to pick up as we get the hang of it!

**Comment by aleallopez** [comment]
thank you!!  and same to you guys good luck

**Comment by KaidyCEThomas** [comment]
Happy Birthday and good luck to you!

**Comment by aleallopez** [comment]
thank youuuu

**Comment by mirenagreen** [comment]
Happ birthday Agnes!! This is also my first time taking programming/online class. I hope we will enjoy it!

**Comment by aalevane** [comment]
Happy belated birthday! My birthday is actually on Friday so we're not too far.

**Comment by hectorsector** [comment]
Great work @aleallopez! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
