### ISSUE TITLE
Jordan-Hosein's Project 1 submission

### ISSUE THREAD

**Issue by Jordan-Hosein** [cop1000/cop1000#70]
Paste your web site's published URL here: https://jordan-hosein.github.io/

Template stolen from: https://github.com/BlackrockDigital/startbootstrap-clean-blog

Check each of the following boxes to ensure you can score :100:
- [X] Bootstrap is used.
- [X] Web site contains images.
- [X] Web site contains text.
- [X] Web site contains external links.
- [X] All of the web site's content can be accessed just by scrolling.
- [X] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [X] The web site contains original content.
- [X] The web site doesn't contain inappropriate content.
- [X] The web site is published to GitHub Pages.
- [X] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Beautiful work, @Jordan-Hosein! ❤️

**Comment by Jordan-Hosein** [comment]
Thanks! : D 
@hectorsector

**Comment by hectorsector** [comment]
Great work @Jordan-Hosein! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
