### ISSUE TITLE
rbowser5's Project 1 submission

### ISSUE THREAD

**Issue by rbowser5** [cop1000/cop1000#73]
Paste your web site's published URL here: 

https://rbowser5.github.io/

Check each of the following boxes to ensure you can score :100:

- [X ] Bootstrap is used.
- [ X] Web site contains images.
- [X ] Web site contains text.
- [X ] Web site contains external links.
- [X ] All of the web site's content can be accessed just by scrolling.
- [X ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [XXXX] The web site contains original content.
- [X ] The web site doesn't contain inappropriate content.
- [X ] The web site is published to GitHub Pages.
- [X ] The link to the web site is submitted in the class repository.

**Comment by lminks** [comment]
I wonder if this is related to the Great Wyoming Conspiracy or if the Japanese are independent actors.

**Comment by hectorsector** [comment]
Great work @rbowser5!

One suggestion (that won't cost you points, just to make your web site better), is to troubleshoot why some of the text is overlapping with the content.

![screen shot 2016-09-29 at 4 28 09 pm](https://cloud.githubusercontent.com/assets/16547949/18971091/c9b83e9c-8661-11e6-8b8a-f7ad151ea1c6.png)

**Comment by hectorsector** [comment]
@rbowser5 I forgot to mention, make sure this requirement is met:

> -[ ] Web site contains external links.

**Comment by hectorsector** [comment]
Great work @rbowser5! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
