### ISSUE TITLE
Vcomney's Project 1 submission

### ISSUE THREAD

**Issue by vcomney** [cop1000/cop1000#74]
Paste your web site's published URL here: 
https://vcomney.github.io/WebsiteProject-1#
Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by Jordan-Hosein** [comment]
The link doesn't lead to a site for me, it tries to download something.

**Comment by vcomney** [comment]
I'm not sure why it is doing that because it works for me when I click it. What was it asking you to download?

**Comment by lminks** [comment]
I think you need to have the main file be named index.html instead of WebsiteProject-1. The link just triggers a download for the WebsiteProject-1 file.

**Comment by Jordan-Hosein** [comment]
Oh yeah, it'll still work. It just downloads and prompts me to open it using a program of my choice. If I choose a browser when it pops up, it loads the page.

**Comment by hectorsector** [comment]
@vcomney please do the following:

1. Rename [this file](https://github.com/vcomney/Vcomney.github.io/blob/master/WebsiteProject-1) to `index.html`.
1. Change the title of this issue to contain your username instead of `YOUR-USERNAME`.

Thanks!

**Comment by vcomney** [comment]
Okay, I think it is fixed now. Thanks!

**Comment by hectorsector** [comment]
@vcomney thanks, I can see your site now, you may want to edit your original post with the new URL which is just https://vcomney.github.io/. Now that I can see your site, I can give you some feedback.

Are these really your photos? They're awesome! Please make sure you meet the following criteria: 

>  Bootstrap is used.
>  Web site contains external links.
>  Users can navigate to different sections of the webpage by clicking buttons in the navigation.

**Comment by hectorsector** [comment]
Great work @vcomney! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
