### ISSUE TITLE
YOUR-USERNAME's Project 1 submission

### ISSUE THREAD

**Issue by cristivela1217** [cop1000/cop1000#75]
Paste your web site's published URL here: 

https://cristivela1217.github.io/

Check each of the following boxes to ensure you can score :100:

- [ 0] Bootstrap is used.
- [ 0] Web site contains images.
- [0 ] Web site contains text.
- [0 ] Web site contains external links.
- [ 0] All of the web site's content can be accessed just by scrolling.
- [ 0] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ 0] The web site contains original content.
- [ 0] The web site doesn't contain inappropriate content.
- [0 ] The web site is published to GitHub Pages.
- [0 ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Good start, @cristivela1217 but please make sure the following requirement is met:

> - [ ] Bootstrap is used.

**Comment by hectorsector** [comment]
Also, please change the title of this issue to include your username.

**Comment by hectorsector** [comment]
Great work @cristivela1217! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
