### ISSUE TITLE
SPierre30's Project 1 submission

### ISSUE THREAD

**Issue by SPierre30** [cop1000/cop1000#77]
Paste your web site's published URL here: https://codepen.io/SPierre30/full/ORgoJA/

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ ] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Hi @SPierre30 please ensure the following requirements are met:

>  Bootstrap is used.
>  Web site contains external links.
>  Users can navigate to different sections of the webpage by clicking buttons in the navigation.
>  The web site is published to GitHub Pages.

**Comment by hectorsector** [comment]
Great work @SPierre30! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
