### ISSUE TITLE
Intro to Prof. Alfaro

### ISSUE THREAD

**Issue by hectorsector** [cop1000/cop1000#8]
Hi all 👋! 

⬅️ You can see my picture on my profile.

I've always been interested in what makes computers work. Doing this for a living and teaching others about it is a dream come true for me! My personal interests include the many Florida theme parks, playing video games, and traveling! I hope to get to know you throughout the semester.

Have an awesome semester 🚀

**Comment by tylerch8** [comment]
Nice to meet you professor! I also share your personal interests. I love my PS4 but not just for the games, but the smart TV features as well. :)

**Comment by aleallopez** [comment]
nice to meet you!!   i love traveling!

**Comment by marxspawn** [comment]
It is a pleasure to meet you :bow: and look forward to learning from you as well :octocat:

**Comment by hectorsector** [comment]
Thanks to everyone that dropped by my introduction post -- I'm closing this now since this assignment has passed 🙇
