### ISSUE TITLE
YOUR-USERNAME's Project 1 submission

### ISSUE THREAD

**Issue by ZPeterson2** [cop1000/cop1000#80]
Paste your web site's published URL here: zpeterson2.github.io

Check each of the following boxes to ensure you can score :100:

- [ ] Bootstrap is used.
- [ ] Web site contains images.
- [ ] Web site contains text.
- [ ] Web site contains external links.
- [ ] All of the web site's content can be accessed just by scrolling.
- [ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ ] The web site contains original content.
- [ ] The web site doesn't contain inappropriate content.
- [ ] The web site is published to GitHub Pages.
- [ ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@ZPeterson2 I don't see any code on your site -- let me know what I can do to help.

**Comment by hectorsector** [comment]
Also, please change the title of this issue to include your username.

**Comment by hectorsector** [comment]
I'm closing this issue as I see you opened #82
