### ISSUE TITLE
YOUR-USERNAME's Project 1 submission

### ISSUE THREAD

**Issue by ZPeterson2** [cop1000/cop1000#82]
Paste your web site's published URL here: https://zpeterson2.github.io/

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@ZPeterson2 Looks great, but please publish on GitHub Pages as was specified in the instructions.

**Comment by ZPeterson2** [comment]
@hectorsector Ok, I fixed the problem.

**Comment by hectorsector** [comment]
![](http://i.giphy.com/kxRcU7cWziLXq.gif)

**Comment by hectorsector** [comment]
Great work @ZPeterson2! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
