### ISSUE TITLE
https://aleallopez.github.io/

### ISSUE THREAD

**Issue by aleallopez** [cop1000/cop1000#83]
Paste your web site's published URL here: https://aleallopez.github.io/

Check each of the following boxes to ensure you can score 💯

  Web site contains images.
 Web site contains text.
 Web site contains external links.
 All of the web site's content can be accessed just by scrolling.
 Users can navigate to different sections of the webpage by clicking buttons in the navigation.
 The web site contains original content.
 The web site doesn't contain inappropriate content.
 The web site is published to GitHub Pages.
 The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@aleallopez I ❤️ the video! 

Just make sure you complete the following requirements: 

> Users can navigate to different sections of the webpage by clicking buttons in the navigation.
