### ISSUE TITLE
jnorris18's Project 1 submission

### ISSUE THREAD

**Issue by jnorris18** [cop1000/cop1000#85]
Paste your web site's published URL here: https://jnorris18.github.io/jnorris18/

Check each of the following boxes to ensure you can score :100:

- [ ] Bootstrap is used.
- [ ] Web site contains images.
- [ ] Web site contains text.
- [ ] Web site contains external links.
- [ ] All of the web site's content can be accessed just by scrolling.
- [ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ ] The web site contains original content.
- [ ] The web site doesn't contain inappropriate content.
- [ ] The web site is published to GitHub Pages.
- [ ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@jnorris18 good start, please make sure the following requirements are met:

>  Users can navigate to different sections of the webpage by clicking buttons in the navigation.

You might also want to ensure that it's published to `yourusername.github.io`, you can do this by renaming your repository to `yourusername.github.io` and ensuring your code is in `index.html`.

**Comment by hectorsector** [comment]
Great work @jnorris18! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
