### ISSUE TITLE
atompkins0's Project 1 submission

### ISSUE THREAD

**Issue by atompkins0** [cop1000/cop1000#86]
Paste your web site's published URL here: http://atompkins0-github.bitballoon.com/

Check each of the following boxes to ensure you can score :100:

- [ ] Bootstrap is used.
- [ ] Web site contains images.
- [ ] Web site contains text.
- [ ] Web site contains external links.
- [ ] All of the web site's content can be accessed just by scrolling.
- [ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ ] The web site contains original content.
- [ ] The web site doesn't contain inappropriate content.
- [ ] The web site is published to GitHub Pages.
- [ ] The link to the web site is submitted in the class repository.

Sorry, I tried for 2 and a half hours to get this uploaded to github and it just gives me an error over and over, the best I could do was connect my github account to bitballoon and upload it there.

**Comment by aalevane** [comment]
You can check off the boxes by putting an x between the brackets and making sure there is no space. Example:
This works: [x]
This does not work: [ x]

**Comment by hectorsector** [comment]
@atompkins0 please ensure the following requirements are met -- please reach out to me on Gitter or this issue and I can help. 

>  Bootstrap is used.
>  Users can navigate to different sections of the webpage by clicking buttons in the navigation.
>  The web site is published to GitHub Pages.

You might also consider removing your address from your web page. Remember that this web page is public and you might not want anyone to see it.

**Comment by hectorsector** [comment]
Great work @atompkins0! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
