### ISSUE TITLE
aalevane's Project 1 submission

### ISSUE THREAD

**Issue by aalevane** [cop1000/cop1000#87]
Paste your web site's published URL here: aalevane.github.io

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@aalevane I ❤️ Unsplash, I'm glad you found it!

My only suggestion would be to resize the images so your web site loads faster -- but that won't cost you any points, just a suggestion.

**Comment by aalevane** [comment]
Thanks for the tip, I'll do that now. Yeah Unsplash was great! I think I spent half the time I was "working" on the assignment just browsing through photos lol.

**Comment by hectorsector** [comment]
Great work @aalevane! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
