### ISSUE TITLE
YOUR-USERNAME's Project 1 submission

### ISSUE THREAD

**Issue by MCastro46** [cop1000/cop1000#89]
Paste your web site's published URL here:  https://mcastro46.github.io/

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by Jordan-Hosein** [comment]
"or something like that" 
Pfft, who plays FFXIV for the shards, it's all about getting the biggest Mount, amirite?

**Comment by Jordan-Hosein** [comment]
http://i1.2pcdn.com/node14/image/article/201410/31/20141031050038a0dxhhi4fwx4qa1u.gif

**Comment by Jordan-Hosein** [comment]
![](http://i1.2pcdn.com/node14/image/article/201410/31/20141031050038a0dxhhi4fwx4qa1u.gif)

**Comment by MCastro46** [comment]
Fat chocobo are the best lmfao a new patch dropped recently u.u

**Comment by MCastro46** [comment]
There's a fat moogle now too  lol

**Comment by hectorsector** [comment]
Looks fantastic @MCastro46!

Please just change the title of your issue.

**Comment by hectorsector** [comment]
Great work @MCastro46! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
