### ISSUE TITLE
[Extra Credit Opportunity] The 11th Hour movie screening Sep 27-29

### ISSUE THREAD

**Issue by hectorsector** [cop1000/cop1000#9]
The College will be [hosting a free screening](http://sustainable.valenciacollege.edu/11th-hour-movie-screening/) of *The 11th Hour*, followed by a facilitated discussion. The focus of this film and conversation will be sustainability and how it applies at Valencia and within the Central Florida community.

### How to Get Credit

First, attend one of the screenings offered:

- Tue, Sep 27, 3-5pm, Osceola Campus
- Wed, Sep 28, 3:30-5:30pm, West Campus
- Thu, Sep 29, 3-5pm, East Campus

Ensure you sign in at the screening you attend so I can verify your attendance. Then, drop a comment in this issue letting me know you attended **no later than Wed, Oct 5**. You'll get the credit in the form of added points to a project. Also drop a comment if you have any questions about this process.

**Comment by hectorsector** [comment]
@cop1000/all-students I'll be at Osceola campus's screening of the film tomorrow, Sep 27, if anyone wants to 👋!

**Comment by Cjwilliams36** [comment]
I will be attending the west campus showing. Where would I sign in?

**Comment by hectorsector** [comment]
Glad to hear it @cjwilliams36. I went today and it was a great experience.

They will ask at the end if anyone needs proof of attendance and they'll take your name and let me know.

**Comment by AntoineDS** [comment]
@hectorsector I went to the extra credit event I received a business card from one if the professor, would you like me to take a picture of the card and send it to you? I did write my name on a piece of paper.

**Comment by hectorsector** [comment]
Thanks @AntoineDS I received an email letting me know you had participated so no extra work is required on your part. 

@cop1000/all-students if you attended one of the movie screenings don't forget to drop a note in this issue to let me know. So far I only have @AntoineDS confirming attendance.

**Comment by hectorsector** [comment]
@AntoineDS your extra credit for this has been added to your project 1 grade #68.

Closing this issue as the event has concluded.
