### ISSUE TITLE
MirenaGreen's Fantastic #1 Project 1 Submission

### ISSUE THREAD

**Issue by mirenagreen** [cop1000/cop1000#90]
Paste your web site's published URL here: [mirenagreen.github.io #1 project](https://mirenagreen.github.io/)

I took inspiration for this website from my absolute favorite travel show- Dora the Explorer. I one day aspire to travel to as many places as she has, and to time my dramatic pauses as well as her.

Template from: http://www.w3schools.com/bootstrap/bootstrap_templates.asp
Font from: https://fonts.google.com/

Check each of the following boxes to ensure you can score :100:

- [X] Bootstrap is used.
- [X] Web site contains images.
- [X] Web site contains text.
- [X] Web site contains external links.
- [X] All of the web site's content can be accessed just by scrolling.
- [X] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [X] The web site contains original content.
- [X] The web site doesn't contain inappropriate content.
- [X] The web site is published to GitHub Pages.
- [X] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Looks fantastic @mirenagreen ❤️

**Comment by hectorsector** [comment]
Great work @mirenagreen! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
