### ISSUE TITLE
Lolivo Project 1 submission

### ISSUE THREAD

**Issue by Lolivo** [cop1000/cop1000#94]
Paste your web site's published URL here: https://lolivo.github.io/

Check each of the following boxes to ensure you can score :100:

- [ ✔] Bootstrap is used.
- [✔ ] Web site contains images.
- [ ✔] Web site contains text.
- [✔ ] Web site contains external links.
- [✔ ] All of the web site's content can be accessed just by scrolling.
- [✔ ] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [ ✔] The web site contains original content.
- [✔ ] The web site doesn't contain inappropriate content.
- [✔ ] The web site is published to GitHub Pages.
- [✔ ] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@Lolivo good start - I love memes! However, please make sure the following requirement is met:

> - [ ] Bootstrap is used.

**Comment by hectorsector** [comment]
Nice work, @Lolivo! Your images now resize on different screen sizes and is mobile ready.

![bootstrap](https://cloud.githubusercontent.com/assets/16547949/19007451/1a2c6e6c-8733-11e6-8623-ff60f366dd8f.gif)

**Comment by hectorsector** [comment]
Great work @Lolivo! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
