### ISSUE TITLE
KaidyCEThomas' Project 1 submission

### ISSUE THREAD

**Issue by KaidyCEThomas** [cop1000/cop1000#95]
Paste your web site's published URL here: https://kaidycethomas.github.io/ 
Codepen version: http://codepen.io/FroLein82/full/VKrxrA/

Check each of the following boxes to ensure you can score :100:

- [x] Bootstrap is used.
- [x] Web site contains images.
- [x] Web site contains text.
- [x] Web site contains external links.
- [x] All of the web site's content can be accessed just by scrolling.
- [x] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [x] The web site contains original content.
- [x] The web site doesn't contain inappropriate content.
- [x] The web site is published to GitHub Pages.
- [x] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
@KaidyCEThomas good start, but please make sure the following requirements are met:

>  Bootstrap is used.
>  Users can navigate to different sections of the webpage by clicking buttons in the navigation.

**Comment by KaidyCEThomas** [comment]
Redo: I've added Bootstrap as well as Jump Page. Thank you!!

**Comment by hectorsector** [comment]
Thanks @KaidyCEThomas. I do see the navigation bar works now. Great work 👍 

However, I don't see how Bootstrap is used.

**Comment by KaidyCEThomas** [comment]
[license.txt](https://github.com/cop1000/cop1000/files/504980/license.txt)
[README.txt](https://github.com/cop1000/cop1000/files/504979/README.txt)

**Comment by KaidyCEThomas** [comment]
@hectorsector I was able to add Bootstrap this time - found out that I didn't check the Bootstrap file in Codepen. Let me know if this works please.

**Comment by hectorsector** [comment]
Great work @KaidyCEThomas! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
