### ISSUE TITLE
robpb24 Project 1 submission

### ISSUE THREAD

**Issue by robpb24** [cop1000/cop1000#98]
Paste your web site's published URL here: https://robpb24.github.io/.github.io/

Check each of the following boxes to ensure you can score :100:

- [√] Bootstrap is used.
- [√] Web site contains images.
- [√] Web site contains text.
- [√] Web site contains external links.
- [√] All of the web site's content can be accessed just by scrolling.
- [√] Users can navigate to different sections of the webpage by clicking buttons in the navigation.
- [√] The web site contains original content.
- [√] The web site doesn't contain inappropriate content.
- [√] The web site is published to GitHub Pages.
- [√] The link to the web site is submitted in the class repository.

**Comment by hectorsector** [comment]
Looks fantastic, @robpb24. If you change your repository name to be `robpb24.github.io` it will serve the web site under the URL https://robpb24.github.io/ instead of the longer URL you see now.

**Comment by hectorsector** [comment]
Great work @robpb24! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
